wenet/transformer/asr_model.py, wenet/transformer/convolution.py, wenet/transformer/ctc.py, wenet/transformer/encoder.py, wenet/utils/mask.py
Change-Id: I07495d8ea4ed9b5ba07150783d0fc65e99251653
=> [doc] refine comment for mask, asr_model, convolution, ctc, encoder

.flake8, .style.yapf, tools/compute-wer.py, tools/merge_scp2txt.py, tools/text2token.py, wenet/bin/average_model.py, wenet/bin/export_jit.py, wenet/bin/recognize.py, wenet/bin/train.py, wenet/dataset/dataset.py, wenet/transformer/asr_model.py, wenet/transformer/attention.py, wenet/transformer/convolution.py, wenet/transformer/decoder_layer.py, wenet/transformer/embedding.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py, wenet/transformer/subsampling.py, wenet/transformer/swish.py, wenet/utils/checkpoint.py, wenet/utils/common.py, wenet/utils/executor.py, wenet/utils/mask.py, wenet/utils/scheduler.py
Change-Id: I9160990f13badddce5e095f5c3d080501806b775
=> [fix] fix code style by flake8

examples/aishell/s0/conf/train_conformer.yaml, examples/aishell/s0/conf/train_transformer.yaml, examples/aishell/s0/conf/train_unified_conformer.yaml, examples/aishell/s0/conf/train_unified_transformer.yaml, wenet/dataset/dataset.py
1. Use un-normalized dither value for  [-32768,32767] waveform
2. convert speed perturbed waveform scaled in [-1,1) to  [-32768,32767]
=> [fix] fix speed perturb and dither related bugs

runtime/server/x86/frontend/wav.h
Allocated array should be deallocated with `delete []` Deallocating it with `delete` can cause memory leaks.
[More info](https://www.viva64.com/en/examples/v611/)
=> [fix] memory leaks

wenet/transformer/asr_model.py
if decoder/ctc is no activate, there is no need to compute
=> move unuse part

wenet/transformer/asr_model.py, wenet/utils/executor.py
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
=> [fix] RuntimeError when ctc_weight=0.0/1.0

tools/compute_cmvn_stats.py
1. change logging from stdout to stderr
2. Training pipeline seems halted without instant logging flush, especially when data-set is large.
=> flush cmvn log in time

runtime/core/decoder/torch_asr_decoder.cc
add function `SplitEachChar`  in `torch_asr_decoder.cc`  to make it possible to support multilingual recipe in the future, in which characters of different languages are all encoded in UTF-8 format.
UTF-8 Reference: https://en.wikipedia.org/wiki/UTF-8#Encoding
=> [runtime] CheckEngWord, support utf8 format

examples/multi_cn/s0/local/tal_mix_data_prep.sh
1. able to filter lines in label file that have only utt and space delimiter but without transcript;
2. transcripts.txt -> transcript.txt
=> [recipe] tal_mix data prep bugfix

tools/fst/compile_lexicon_token_fst.sh
Error code is masked in the pipeline, such as 
```ctc_token_fst.py ... | ...```
=> Masked error code

runtime/core/decoder/torch_asr_decoder.cc, runtime/core/decoder/torch_asr_decoder.h
If `symbol_table_` loads from an English word piece file, then the following may occur:
```
▁p 1
ar 2
k 3
```
if hypothesis is `1 2 3`, then `path.sentence` will be "▁par k" (beacuse "ar" an "k" are both english word), after processing by `ProcessBlank` the final result is "par k".
=> fix the problem of incorrectly inserting spaces in the case of English word piece

runtime/core/frontend/fbank.h, runtime/core/frontend/fft.cc, runtime/core/frontend/fft.h
fft may crash in multi-threaded scenarios:
e.g.
```
last_n = 0
thread1:
1) if (n != last_n || n == 0)  pass
2) make_sintbl/make_bitrev
3) access bitrev and sintbl
thread2:
1）if (n != last_n || n == 0)  pass
2) if (sintbl != NULL) free(sintbl);
```
if the order is:
- thread1: 1
- thread2: 1
- thread1: 2
- thread2: 2
- thread1: 3 (crash because `sintbl` has been freed )
=> [runtime] create bitrev and sintbl for each feature pipeline

runtime/core/grpc/grpc_server.cc
fixed the problem: wordpieces array only a wordpiece element return in gRPC server.
=> fixed bug: wordpieces array only a wordpiece element return.

tools/compute_cmvn_stats.py, tools/wav2dur.py, wenet/dataset/dataset.py, wenet/dataset/wav_distortion.py
sox backend is removed in torchaudio 0.9.0
=> Update to sox_io backend and replace deprecated load_wav

examples/multi_cn/s0/run.sh
The label in `${feat_dir}_${en_modeling_unit}/test_${x}/text` contains '▁', but the hyp in `$test_dir` doesn't,
'▁' has been removed by `sed`. The former method will increase wer in Other -> 100.00 %.
=> fix wer compute in run.sh

examples/multi_cn/s0/local/aishell2_data_prep.sh
*Seems that the generated tmp_trans.txt of AISHELL2 with \t\space as separation is causing unexpected behavior during the tokenization process, finally creates an insane BPE vocab size of 1 million mixing with those AISHELL2 utter ids
*So I fix it by correcting the data preparation script for AISHELL2
=> Fix a bug in recipe multi_cn which causes very large vocab size

examples/multi_cn/s0/run.sh
We need use `sed 's/\([A-Z]\) \([A-Z]\)/\1▁\2/g'` twice . 
eg: a="哈哈 A B C D"
`echo $a | sed 's/\([A-Z]\) \([A-Z]\)/\1▁\2/g'` -> output: `哈哈 A▁B C▁D`
`echo $a | sed 's/\([A-Z]\) \([A-Z]\)/\1▁\2/g'| sed 's/\([A-Z]\) \([A-Z]\)/\1▁\2/g'` -> output: `哈哈 A▁B▁C▁D`
`if $en_modeling_unit = "bpe"` is not bash syntax and we don't need spm_decode here.
=> fix bash syntax & update multi_cn clean text

wenet/dataset/dataset.py
sox_io_backend.load param offset should be frame_offset.  It's similar to PR [#541](https://github.com/wenet-e2e/wenet/pull/541)
=> Correct the param of sox_io_backend.load in dataset.py

examples/aishell/s3/conf/train_conformer.yaml
It requires too long time to load the data if the shuffle size is too big.
=> [conf] update shuffle size

wenet/bin/train.py
Prefetch is very important in the new IO system, especially  for the distributed training.
If the prefetch factor is small, the training may be blocked since the upstream pipeline is still buffering data(like shuffle/sort in our pipeline)
prefetch很小的时候还是不能解决卡顿问题，因为前面某一级还在缓存数据。
=> [network] add prefetch in training

wenet/bin/recognize.py
When training with dynamic batch size, batch type at decoding will also be set to "dynamic". This may cause assertion error because decoding batch size must be 1.
=> fix recognize's batch type error

wenet/dataset/dataset.py
using index list for sampling instead of source list, reduces almost half memory of  data.list occupied.
=> considerably reduce memory usage

wenet/bin/recognize_onnx.py
Signed-off-by: slyned <slyned@nvidia.com>
Add script for recognizing the exported onnx models.
Both GPU & CPU are supported in onnxruntime.
Usage:
```bash
python3 wenet/bin/recognize_onnx.py --config=20210618_u2pp_conformer_exp/train.yaml --test_data=raw_wav/test/data.list --gpu=0 --dict=20210618_u2pp_conformer_exp/words.txt --mode=attention_rescoring --reverse_weight=0.4 --ctc_weight=0.1 --result_file=./att_res_result.txt --encoder_onnx=onnx_model/encoder.onnx --decoder_onnx=onnx_model/decoder.onnx
```
=> add recognize_onnx.py

examples/librispeech/s0/run.sh
The decoding pass was including the key column and treating it as text, so the result was malformed.
=> [examples] fix librispeech decoding bpe

wenet/bin/export_onnx.py, wenet/bin/recognize_onnx.py
1. Fix model with only left to right decoder.
2. Add scoring function to rescore decoder.
3. Add cmvn_file option to export_onnx.py so that users don't need edit cmvn path in train.yaml.
3. Tested pretrained models in wenetspeech (2 models) and aishell2 (4 models).
4. The accuracy of pretrained models in wenetspeech seems better than the official published ones. (~0.06 cer better)
5. Found 'constant-folding' warning will only appear in models with 'causal:True'.
6. Found the dataset configs in aishell2 last three pretrained models (u2_transformer, unified_conformer, unified_transformer) are old ones. 
7. Found no cmvn file in 20211025_conformer_bidecoder_exp.tar.gz
=> Fix onnx export

wenet/bin/train.py, wenet/utils/executor.py
Aishell test Accuracy with fp16_grad_sync enabled:
ctc greedy: 5.09
ctc prefix: 5.09
attention: 4.99
rescore: 4.69
It could improve training speed from 17 hours/100 epochs to 11 hours/100 epochs, especially for multi-nodes training.
My training environment:
two nodes with 6 gpus per node. eth0 Speed: 10000Mb/s
=> [src] Add Fp16 grad sync for ddp

runtime/core/bin/decoder_main.cc
Add endpoint status reset in decoder_main to avoid errors due to too long audio.
=> add endpoint reset in runtime/core/bin/decoder_main.cc

test/test_tokenize.py, wenet/bin/recognize.py, wenet/bin/train.py, wenet/dataset/dataset.py, wenet/dataset/processor.py, wenet/utils/file_utils.py
resolves https://github.com/wenet-e2e/wenet/issues/796
=> Support non-linguistic symbol in uio

examples/wenetspeech/s0/README.md
Signed-off-by: slyned <slyned@nvidia.com>
Add other models' perf as notes
U2 ++  conformer 26 epochs:
| Decoding mode - Chunk size    | Dev  | Test_Net | Test_Meeting |
|-------------------------------|------|----------|--------------|
| ctc greedy search - full      | 9.16 | 10.38    | 17.77        |
| ctc greedy search - 16        | 9.54 | 11.66    | 18.70        |
| ctc prefix beam search - full | 9.09 | 10.33    | 17.59        |
| ctc prefix beam search - 16   | 9.48 | 11.60    | 18.57        |
| attention rescoring - full    | 8.84 | 9.79     | 17.29        |
| attention rescoring - 16      | 9.08 | 10.83    | 18.06        |
ctc_weight: 0.5  reverse_weight: 0.3
Unified conformer(single decoder), 26 epochs:
| Decoding mode - Chunk size    | Dev   | Test_Net | Test_Meeting | …
=> add wenetspeech u2++ model perf

runtime/core/decoder/ctc_prefix_beam_search.cc, runtime/core/decoder/ctc_prefix_beam_search.h
Handle the context that has not yet the end boundary does not set to start state with negative score at the end of ctc prefix search at the end of ctc prefix search.
See the issue #864.
=> Handle the context that has not yet the end boundary does not set to start state with negative score 

wenet/transformer/decoder.py, wenet/transformer/decoder_layer.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py, wenet/transformer/subsampling.py
Signed-off-by: slyned <slyned@nvidia.com>
NAN will occur when using model.half() to do inference.
The issue is reported here: https://github.com/pytorch/pytorch/issues/41527
1. Changed all eps=1e-12 to 1e-5 a default value for [torch.nn.functional.layer_norm](https://pytorch.org/docs/stable/generated/torch.nn.LayerNorm.html).
=> change layer norm to use default eps

examples/librispeech/s0/conf/train_conformer.yaml, examples/librispeech/s0/conf/train_conformer_bidecoder_large.yaml, examples/librispeech/s0/conf/train_u2++_conformer.yaml, examples/librispeech/s0/conf/train_unified_conformer.yaml
The relevant parameters in filter_conf (min_output_input_ratio: 0.05, max_output_input_ratio: 10.0) are given as percentages.
But the filter class (wenet.dataset.processor.filter) does not treat them as expected.
=> [fix] Update filter_conf

runtime/core/bin/decoder_main.cc, runtime/core/decoder/ctc_prefix_beam_search.cc
`cur_hyps_` will add an empty hypotheses after Reset() function.
https://github.com/wenet-e2e/wenet/blob/ea81aaad6421601428b3d0d6745176616bb46b36/runtime/core/decoder/ctc_prefix_beam_search.cc#L36
=> fix(decoder): fix check bug of decoder_main in continuous decoding mode

runtime/core/decoder/ctc_prefix_beam_search.cc
`outputs_` should also have an empty result after `Reset()`.
https://github.com/wenet-e2e/wenet/blob/9a4efbe9631b813804f2aca8d9f66fde722b6ef5/runtime/core/decoder/torch_asr_decoder.cc#L193
https://github.com/wenet-e2e/wenet/blob/9a4efbe9631b813804f2aca8d9f66fde722b6ef5/runtime/core/decoder/torch_asr_decoder.cc#L195
https://github.com/wenet-e2e/wenet/blob/9a4efbe9631b813804f2aca8d9f66fde722b6ef5/runtime/core/decoder/torch_asr_decoder.cc#L199
=> fix(decoder): fix check bug of ctc_prefix_beam_search

wenet/utils/config.py
Fix override-config bug when override item type is boolean. [#709 ](https://github.com/wenet-e2e/wenet/pull/709)
=> fix override-config bug when override item type is boolean.

runtime/core/decoder/torch_asr_model.cc, runtime/core/decoder/torch_asr_model.h, wenet/transformer/asr_model.py, wenet/transformer/attention.py, wenet/transformer/convolution.py, wenet/transformer/decoder_layer.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py
Model: Aishell-1 u2++ Conformer (with **dynamic quantization**)
Config: num_bins 80, ctc_weight 0.3, rescoring_weight 1.0, reverse_weight 0.5
Test-set: Aishell-1 test-set, 7176 sentences
| API   | chunk_size | num_left_chunks | RTF(OMP_NUM_THREADS=1) | WER(int8) | WER(float32) |
|-|-|-|-|-|-|
| old   | -1 | -1  |  0.05871  |  4.89 %  |  4.68 %  |
|         | 16 | -1  | 0.1057 |  5.27 %    | 5.07 % |
|         | 16 | 4   | 0.08996  |  5.73 % | 5.60 %  |
| new | -1  | -1  |  0.05859 | 4.89 %  | 4.68 % |
|         | 16 | -1  | 0.07453 | 5.19 %  | 5.07 % |
|         | 16 | 4   | 0.07064  | 5.68 %  | 5.60 % |
Model: Aishell-1 u2++ Conformer
Config: num_bins 80, ctc_weight 0.3, rescoring_weight 1.0, reverse_weight 0.5
Test-set: Aishell-1 test-set, 7176 sentences
| API   | chunk_size | …
=> [model] new API for efficient cache control

README.md, docs/papers.md
In order to simplify referrence for users, I deleted some of our articles that are not complete like U2/U2++/Production First ..., I 
only keep the two papers WeNet 1.0/2.0 which are well finished, and accepted or submitted to Conferrence.
=> [doc] update referrence paper

wenet/transformer/encoder.py
In https://github.com/wenet-e2e/wenet/pull/1002, I only test `forward_chunk_by_chunk` with attention_rescoring and it works well. However, when decoding with ctc_greedy_search, shape of encoder_mask cannot be (0, 0, 0), because it will be 
used to calculate encoder_out_lens. see https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L318
=> [fix] fix bug in forward_chunk_by_chunk(ctc_greedy_search)

wenet/bin/export_onnx_cpu.py, wenet/transformer/attention.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py
I find it quite easy to export onnx (either streaming model or non-streaming model) within our recently developed new cache API. The most tricky thing for onnx export is to ensure that all if-else branches in `forward_chunk` will always take the same path with a given decoding setup (i.e., 16/-1, 16/4, 16/0 or -1/-1) (this will turn the dynamic if-else branch into a static branch and `next_cache_start` will be a fixed value). To do this, we can simply adjust the shape of cache & mask tensors for the **first** input chunk according to `chunk_size` and `num_left_chunks`.
1. Why don't we need `jit.script` for if-else branches?
As mentioned above, we force our model to select the same branch for every chunk.
2. Why don't we need `jit.script` for tensor slice?
**From @Mddct ** : ONNX supports …
=> [bin] onnx_streaming and onnx_non_streaming

runtime/core/decoder/ctc_prefix_beam_search.cc
fix CHECK_EQ(input.size(), time_stamp.size()) failed
related pr and discussion:
https://github.com/wenet-e2e/wenet/pull/991
https://github.com/wenet-e2e/wenet/pull/1051
=>  fix CHECK_EQ(input.size(), time_stamp.size()) failed

tools/make_shard_list.py
According to [pytorchaudio issues](https://github.com/pytorch/audio/issues/2294), resample can't process the int audio.
And `waveforms, sample_rate = sox.load(wav, normalize=False)`, so the type of waveforms from wav is int16.
Therefore normalize the audio before resample by dividing (1<<15).
=> [tools] normalize the audio before resample

wenet/bin/export_onnx_cpu.py, wenet/transformer/asr_model.py, wenet/transformer/attention.py
1. Instead of manually popping out input nodes according to different `chunk_size/num_left_chunks`, we now read in/out nodes from model.onnx and save their names, names are then used to decide which tensor should be poped.
2. We keep dynamic axes even if in 16/4 mode, this is to avoid padding the last chunk (which usually contains less frames than required). For users who want static axes, just pop out specific axis.
3. Fix bug when exporting Bi-rescore decoder.
=> [refactor] update&bugfix, onnx_cpu

runtime/core/decoder/asr_decoder.cc, runtime/core/decoder/asr_decoder.h
I have some confusions in my pr, time_stamp_gap_ is not a well variable to define its value, or just use frame_shift_in_ms(), maybe time_stamp_gap_ move to param.h that can be configured.
here just use a gap to limit word align timestamp more accurate, I think if combine blank timestamp, the result will better, but that seems too hard.
=> fix word alignment timestamp

runtime/core/decoder/onnx_asr_model.cc, runtime/core/decoder/onnx_asr_model.h, runtime/core/decoder/params.h
We thank @Mddct  and @Duum for the hints to fix non-streaming bugs and the explanations behind those changes.
| chunk_size / num_left_chunks | bi-rescore WER(onnx) | bi-rescore WER(torch) | 
|-|-|-|
| -1 / -1 (export from streaming model) | 4.63 % N=104765 C=100008 S=4626 D=131 I=89 | 4.63 (examples/aishell/s0/READEME) |
=> [runtime] fix bug of onnx non-streaming

runtime/core/cmake/onnx.cmake, runtime/core/decoder/onnx_asr_model.cc
Please see:
* https://github.com/microsoft/onnxruntime/issues/11480
* https://github.com/microsoft/onnxruntime/issues/6243
=> [runtime] copy onnx dlls to cmake_binary_dir

wenet/transformer/decoder_layer.py, wenet/transformer/encoder_layer.py, wenet/utils/checkpoint.py
Hi,
I find some unused parameters at [`wenet/wenet/transformer/encoder_layer.py`](https://github.com/wenet-e2e/wenet/blob/6f884838c460510d8f6943ce1a3bc908ee40d349/wenet/transformer/encoder_layer.py#L55) and [`wenet/wenet/transformer/decoder_layer.py`](https://github.com/wenet-e2e/wenet/blob/6f884838c460510d8f6943ce1a3bc908ee40d349/wenet/transformer/decoder_layer.py#L55).
The default configuration of `concat_after` is `False`. 
This will lead the `self.concat_linear` to be unsed and bring redundancy in whole Conformer network.
Therefore, I add if statements to fix this problem.
=> [model] fix unused parameters in `encoder_layer.py` and `decoder_layer.py`

runtime/core/decoder/params.h, runtime/core/kaldi/decoder/lattice-faster-decoder.cc, runtime/core/kaldi/decoder/lattice-faster-decoder.h, tools/decode.sh
In TLG equipped decoder called 'ctc_wfst_beam_search', the del/ins error ratio is much higher than the one without it called 'ctc_prefix_beam_search'
This PR provides a solution to add length penalty in TLG fst path. Penalty only add on the node where a new word occurs. Besides, it also considered the penalty when caculating beam cut weight.
I also notice another potential solution  to add delete penalty in process noemitting function, but it is added on every new node(i lable=0). It may cause some misunderstanding because a word may last for a long time. See [delete penalty](https://github.com/wenet-e2e/wenet/pull/994)
By comparision, my solution performs better than it. I realize and test both solutions, tables below are the comparison result.
These experiments are performed on …
=> add length penalty

wenet/transformer/encoder.py
when `pos_enc_layer_type = "abs_pos"`, conformer should use `MultiHeadedAttention` rather than `RelPositionMultiHeadedAttention`.
[here](https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/encoder.py#L427)
=> Fix absolute position encoding in conformer.

runtime/LibTorch/README_CN.md
The file name in command
```bash
wget https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/aishell/20210601_u2%2B%2B_conformer_libtorch.tar.gz
```
is different from command
```
tar -xf 20210602_u2++_conformer_libtorch.tar.gz
model_dir=$PWD/20210602_u2++_conformer_libtorch
```
This PR fix this.
=> [doc]: fix model path

tools/install_srilm.sh
I was not able to use `tools/install_srilm.sh` and found a typo.
`! -f` instead of `-z` to test whether the file exists.
=> Fix a typo

.github/workflows/doc.yml
Because `sphinx-markdown-tables` is updated.
Plz see https://github.com/ryanfox/sphinx-markdown-tables/commit/ae777bde2ca9c0ccfbdb90d6270897b4cd27d12b
=> Revert "[workflows] Fix markdown version of doc"

tools/fst/compile_lexicon_token_fst.sh
use ctc_token_fst_compact.py to replace ctc_token_fst.py
=> [tools] make T.fst support empty sentence

runtime/onnxruntime/README.md
run wenet/bin/export_onnx_cpu.py as package, otherwise `ModuleNotFoundError: No module named 'wenet'`.
=> [doc] update onnxruntime README

runtime/gpu/Dockerfile/Dockerfile.client, runtime/gpu/Dockerfile/Dockerfile.server
when building gpu triton server docker, i met a problem:
```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed.
```
so i add a new line in the dockerfile:
`RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub`
=> Fix GPU Runtime build error

examples/aishell2/s0/local/word_segmentation.py
The output of ```awk '{$1,99}'``` should be like ```xxx 99```.
=> fix bug: aishell2 word_segmentation.py

tools/fst/compile_lexicon_token_fst.sh
If a word in lexicon.txt has several pronunciations, the words.txt maybe contains duplicate symbols.
So, add `uniq` to avoid that
=> [tools] fix compile_lexicon_token_fst.sh to avoid duplicate symbols

examples/aishell/s0/README.md, examples/aishell/s0/run.sh, tools/k2/make_hlg.sh, tools/k2/prepare_char.py, wenet/bin/recognize.py, wenet/transformer/asr_model.py
We add hlg decode using k2. Now we can use k2 to compile a HLG, and decode using python with cuda.
We provide two decoding algorithm. One is onebest, which is same as ctc_prefix_beam_search with lm score, another is attention rescore.
Notice that in attention rescore, we have 3 different scale parameter, which are lm_scale, decoder_scale and r_decoder_scale.
Special thanks to K2 groups great work!
=> add hlg decode

wenet/utils/common.py
In the comment of function "th_accuracy", the shape of "pad_targets" should be (B, Lmax).
=> Fix comment error.

runtime/core/decoder/asr_decoder.cc, runtime/core/decoder/ctc_wfst_beam_search.cc, runtime/core/decoder/ctc_wfst_beam_search.h, runtime/core/decoder/params.h
blank scale can smooth wfst decoding score
=> add blank scale for wfst decoding

tools/fst/prepare_dict.py, wenet/utils/scheduler.py
tools/fst/prepare_dict.py, it can't split chinese phrase into character when bpemodel given [issus](https://github.com/wenet-e2e/wenet/issues/1653).  Now It can process english and chinese in one lexicon.txt .
=> [fix] prepare_dict support english and chinese in one lexicon.txt

runtime/binding/python/CMakeLists.txt, runtime/binding/python/setup.py, runtime/core/api/CMakeLists.txt, runtime/core/api/wenet_api.cc
For aarch64 systems (raspberry pi, horizonx3 pi, etc), ort backend is a better choice. 
Test success on x3 pi: 
TODO (in next PR, not this one):
=> [runtime/binding] support ort backend in wenetruntime

examples/aishell/s0/README.md, examples/aishell/s0/run.sh, tools/k2/prepare_mmi.sh, wenet/bin/train.py, wenet/transformer/asr_model.py, wenet/utils/init_model.py
add LFMMI loss, add torch.jit.ignore for lfmmi function
=> add LFMMI loss

wenet/transducer/transducer.py, wenet/utils/init_model.py
Encounter such error when run aishell/rnnt/run.sh 
_File "/wenet/wenet/wenet/transducer/transducer.py", line 42, in __init__
super().__init__(vocab_size, encoder, attention_decoder, ctc,
File "/wenet/wenet/wenet/transformer/asr_model.py", line 60, in __init__
assert 0.0 <= ctc_weight <= 1.0, ctc_weight
AssertionError: -1_
It is missing lfmmi dir args when init transducer model.
=> transducer model init has no lfmmi dir

tools/k2/prepare_mmi.sh
This is a typo.  Should change train_dir to dev_dir, or it will result compose fail and loss inf in dev stage
=> fix lfmmi script typo

wenet/utils/ctc_util.py
Different from the "prev_state" or "state_path" variable which indicates it recording the previous state of one point, the original "prev_state" in lines 74-75 should indicate the chosen final state rather than its predecessor. Try to disambiguate.
=> (Minor) Update ctc_util.py named variable

test/test_tokenize.py, wenet/ssl/bestrq/bestqr_model.py, wenet/ssl/bestrq/mask.py
changes:
-  stack fbank instead of stack features after subsampling  （BEST-RQ paper do stack fbank ）
-  replace compute_mask_indices_v2 with compute_mask_indices,(v2 from wav2vec2  which compute mask in cpu), The v2 version can consider padding, and the probability of short sequence overmask becomes smaller
- fbank should do cmvn ， stack fbanks should renorm using unlearnable LN  avoiding codebooks collapse
- add fbank l2 regularization which can stable training
- other info about training
- reset encoder parameter using bert-style:  trunk_norm std==0.02
=> [bestrq] stable training

wenet/dataset/processor.py
Check this [issue](https://github.com/pytorch/audio/issues/2948)
I encounter this issue by using shard to do training on flacs files... Notice the issue only occurs when using torchaudio to load a file-like object not a file path.
=> Fix - FLAC ERROR whilst decoding metadata

examples/aishell/s0/conf/ds_stage2.json, examples/aishell/s0/conf/train_u2++_conformer_1.8B.yaml, examples/aishell/s0/run.sh, requirements.txt, tools/filter_uneven_data.py, wenet/bin/train.py, wenet/utils/executor.py
This PR integrates Deepspeed into wenet, which enables:
1. faster training (~10% speedup) on **small models** (i.e., standard conformer with 48M (0.048B) params)
2. ability to train **much larger models** (i.e., using deepspeed's zero optimization, we can train ~2B model without pain)
| mode             | ctc greedy   | rescore | comment |
|---------------------------|-------|------|-------|
| torch.ddp         | 5.19  | 4.63 | chunk -1, 360 epoch, batch16, 8GPUs, following standard u2pp_conformer [config](https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/s0/conf/train_u2%2B%2B_conformer.yaml) |
| deepspeed         | 5.15 | 4.82 | chunk -1, 360 epoch, batch32, 4GPUs, following standard u2pp_conformer [config](https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/s0/conf …
=> feat(train): support deepspeed

runtime/onnxruntime/README.md
Remind the user to align the chunksize/leftchunks in the decoder flag with the chunksize/leftchunks used for exporting ONNX models; otherwise, it may result in a segmentation fault.
=> [doc/onnxruntime] Update README.md

tools/make_shard_list.py
fix issue https://github.com/wenet-e2e/wenet/issues/1932
=> fix(dataset): Fix bug when make shard.list for *.flac

runtime/core/decoder/context_graph.cc
修复runtime context graph在使用英文热词时会给每个bpe字词添加“▁”的问题，并且为英文热词设置热词分数时不再乘以token长度。
修复解码过程中热词匹配到一半时失配需要消耗一个token的问题。该问题导致对于“唯品唯品会”无法匹配热词“唯品会”，对于大热词列表以及识别英语情况下影响会比较大，因为这两种情况中更容易进入热词匹配的过程，也就会产生更多的失配，影响正常的热词增强过程。
Librispeech test-other测试集，使用attention rescoring解码应用热词图前后结果，由于runtime context graph方案中是按照词表直接对热词进行bpe分词，所以效果会比python context graph差一些：
method | WER | U-WER | B-WER
-- | -- | -- | --
baseline | 8.77 | 5.58 | 36.84
python context graph | 7.9 | 5.61 | 28.02
old runtime context graph | 8.42 | 5.71 | 32.19
new runtime context graph | 8.14 | 5.63 | 30.19
热词列表大小3838，合并了test-other每条数据包含的热词，context score=2.0
热词列表路径：https://github.com/facebookresearch/fbai-speech/tree/main/is21_deep_bias
=> [fix] fix runtime context graph

wenet/transducer/predictor.py, wenet/transducer/transducer.py
fix some error
1. when use k2, predictor's output_size shoud return
2. about delay_penalty
=> [RNN-T] transducer's simple_lm_proj shoud be predictor.output_size and delay_panalty is 0 when step less than 2*warmup_step

examples/aishell/s0/README.md, examples/aishell/s0/conf/train_ebranchformer.yaml, wenet/branchformer/cgmlp.py, wenet/e_branchformer/encoder.py, wenet/e_branchformer/encoder_layer.py, wenet/utils/init_model.py
Hi,
This PR is about the [E-Branchformer](https://arxiv.org/abs/2210.00077). Modified based on [Branchformer implementation](https://github.com/wenet-e2e/wenet/pull/1845).
The results as follows：
* Feature info: using fbank feature, dither=1.0, cmvn, online speed perturb
* * Model info:
* Model Params: 47,570,132
* Num Encoder Layer: 17
* CNN Kernel Size: 31
* Training info: lr 0.001, weight_decay: 0.000001, batch size 16, 4 gpu, acc_grad 1, 240 epochs
* Decoding info: ctc_weight 0.3, average_num 30
* Git hash: 89962d1dcae18dd3a281782a40e74dd2721ae8fe
| decoding mode          | CER  |
| ---------------------- | ---- |
| attention decoder      | 4.73 |
| ctc greedy search      | 4.77 |
| ctc prefix beam search | 4.77 |
| attention rescoring    | 4.39 |
| LM + attention rescoring  | 4.22  |
=> Add E-Branchformer module

examples/aishell/s0/run.sh, wenet/bin/train.py
=> [wenet] use torchrun for distributed training

wenet/ssl/bestrq/bestrq_model.py, wenet/ssl/wav2vec2/quantizer.py, wenet/ssl/wav2vec2/wav2vec2_model.py
act subsampling as  feature extraction for wav2vec training  
plz ref  to https://github.com/wenet-e2e/wenet/pull/1003 for more info
=> [ssl/wav2vec2] support wav2vec2 

wenet/ssl/wav2vec2/wav2vec2_model.py
=> [ssl/wav2vec2]  add more info

wenet/ssl/w2vbert/w2vbert_model.py, wenet/ssl/wav2vec2/quantizer.py, wenet/ssl/wav2vec2/wav2vec2_model.py
ref: https://arxiv.org/pdf/2108.06209v2.pdf
note: bestrq >= w2vbert >= hubert >= wav2vec2 from some public information，
btw：  HuBERT, which relies on an iterative re-clustering and re-training process， so no plan to implement hubert for now
=> [ssl/w2vbert]  support part of w2vbert training

setup.cfg, setup.py, wenet/cli/hub.py, wenet/cli/transcribe.py
It works! 这个是第一个版本，后续我们可以在这个基础上不断支持新的功能，例如：
* 热词
* 对齐
* 时间戳
* 长语音
* onnx 模型，方便 ARM 等平台使用
等等。
为什么要作纯基于 python 版本的 cli 的工具？因为
1. 纯 python 安装等环境问题会少很多，绝大部分情况均可以开箱即用，而 wenetruntime 则环境问题诸多。
2. 纯 python 开发迭代速度更快，对开发者更友好。
最终，在易用性和间接性上，我们期望对标 whisper。
=> [cli] add first wenet cli

wenet/transformer/asr_model.py, wenet/transformer/search.py
Move all search methods to search.py to keep the training code as clean/simple as possible. 
后续在该 PR 基础上会进一步作重构：
* 传入解码方式为列表，支持 ctc_greedy_search, ctc_prefix_beam_search, attention, attention_rescoring 等，asr_model.py 和 recognize.py 的代码量都能大幅度精简。
* 所有解码方式共享网络前向，可一次前向，不同方式解码，节省开销。
=> [wenet/transformer] move search methods to search.py

wenet/ssl/bestrq/bestrq_model.py
ref https://github.com/wenet-e2e/wenet/issues/1997
该pr可以让模型在较大学习率下稳定训练， 比如0.01， 之前实现会有不稳定现象，并且学习率需要小于5e-4才可以并且性能有影响
TODO:
=> [ssl/bestrq] model and numerical stability

wenet/bin/recognize.py, wenet/transformer/asr_model.py, wenet/transformer/search.py
Test result on AIShell-1:
We only support batch size 1 in the old system in decoding, add add batch support in https://github.com/wenet-e2e/wenet/pull/2059. Compared with the old system with batch size 1, there is about **4** times speedup.
=> [transformer] refactor and simplify decoding methods

wenet/cli/model.py, wenet/cli/transcribe.py, wenet/transformer/search.py
=> [cli] support confidence in cli

wenet/cli/hub.py, wenet/cli/paraformer_model.py, wenet/cli/transcribe.py
=> [cli] support download model from modelscope

examples/aishell/s0/run.sh, wenet/bin/train.py, wenet/utils/executor.py, wenet/utils/init_model.py, wenet/utils/train_utils.py
- split `train.py` & `executor.py` into multiple unified API calls and move those API into `train_utils.py`
- launch `torchddp` & `deepspeed` via torchrun
A known issue of deepspeed: https://github.com/microsoft/DeepSpeed/issues/4298
=> refactor(deepspeed): Refine traning code

wenet/bin/train.py, wenet/dataset/processor.py, wenet/utils/executor.py, wenet/utils/train_utils.py
This provides flexibility and simplifies the code. It is a follow-up PR from https://github.com/wenet-e2e/wenet/pull/2055
=> refactor(dataset): return dict instead of tuple

wenet/bin/alignment.py, wenet/bin/export_ipex.py, wenet/bin/export_jit.py, wenet/bin/export_onnx_bpu.py, wenet/bin/export_onnx_cpu.py, wenet/bin/export_onnx_gpu.py, wenet/bin/recognize.py, wenet/paraformer/export_jit.py, wenet/utils/init_model.py
=> fix(bin): init_model API changed

setup.py
'numpy'  in ctc_utils.py
'requests' in  hub
=> [cli] missing 'requests' and 'numpy'

wenet/cli/model.py, wenet/cli/transcribe.py, wenet/transformer/search.py, wenet/utils/context_graph.py
热词列表:
```
荣誉伟
北京
人民大会堂
嗨小奇
```
```
base) ➜  wenet git:(chengdong-context) ✗ wenet --language chinese ../1000003_0f90da0d.wav --context_path ../context_path.txt --context_score 3.0         
{'text': '日本内阁官房长官荣誉伟表示', 'confidence': 0.5924476210863998}
(base) ➜  wenet git:(chengdong-context) ✗ wenet --language chinese ../1000003_0f90da0d.wav                                                       
{'text': '日本内阁官房长官荣誉为表示', 'confidence': 0.8130293280382528}
```
@pkufool, 这里我们搬运了你的代码。
=> [cli] support context biasing with ac automaton

wenet/bin/export_jit.py
missing eval
https://github.com/wenet-e2e/wenet/pull/2127 这里导出加了的话， cli model里边不用eval应该就可以了
https://github.com/wenet-e2e/wenet/blob/main/wenet/paraformer/export_jit.py#L59 paraformer导出用了这个 infer没有这个问题
=> [wenet] export_jit.py

tools/make_shard_list.py
在tool/make_shard_list.py中
原始代码：
if sample_rate != resample:
audio = torchaudio.transforms.Resample(
sample_rate, resample)(audio)
修改后代码：
if sample_rate != resample:
audio = torchaudio.transforms.Resample(
sample_rate, resample)(audio.float())
audio = audio.to(torch.int16)
=> [fix]fix the type error in make_shard_list.py when resample(#2125)

wenet/bin/recognize.py, wenet/transformer/asr_model.py
热词列表：
```
荣誉伟
北京
人名大会堂
```
```bash
python wenet/bin/recognize.py --modes "attention_rescoring" --config 20220506_u2pp_conformer_exp/train.yaml --data_type "raw" --test_data data.list --checkpoint 20220506_u2pp_conformer_exp/final.pt  --dict 20220506_u2pp_conformer_exp/units.txt --result_dir result
2023-11-12 22:28:37,392 INFO attention_rescoring 1000003_0f90da0d.wav 日本内阁官房长官荣誉为表示
python wenet/bin/recognize.py --modes "attention_rescoring" --config 20220506_u2pp_conformer_exp/train.yaml --data_type "raw" --test_data data.list --checkpoint 20220506_u2pp_conformer_exp/final.pt  --dict 20220506_u2pp_conformer_exp/units.txt --result_dir result --context_graph_score 6.0 --context_list_path hotword.txt --context_bias_mode decoding-graph
2023-11-12 22:29:16,374 INFO attention_rescoring …
```
=> [wenet] support context biasing in bin/recognize.py

wenet/utils/checkpoint.py
`strict=False` 遇到不匹配的不会报错，而是直接pass，出现bug会很难察觉（比如有些tensor在ckpt中没有，但是用户以为有且做了正确初始化）
=> feat(ckpt): print more info for debug when loading state_dict

examples/aishell/s0/run.sh
`run.sh` 中开头有dict=xxxxx, 如果这里没换成 `${dict}` ,则开头的设置实际上不会起作用
=> fix(example): correct symble table

wenet/transformer/ctc.py, wenet/utils/init_model.py, wenet/utils/train_utils.py, wenet/whisper/convert_whisper_to_wenet_config_and_ckpt.py
1. whisper没有单独的blank id（未来要引入的llm，其词表应该也是没有blank id的），因此ctc需要能够指定非0的blank id （whisper的id=0对应的是个感叹号）
2. （暂时）指定 `50362` 为 blank_id, 是因为whisper这个对应了一个特殊token `<nospeech>`，做ASR微调的时候decoder输入永远不会出现这个token（VAD任务才会有），且含义上也比较接近ctc的blank
=> fix(whisper): support arbitrary ctc blank id

wenet/whisper/convert_whisper_to_wenet_config_and_ckpt.py
使用decode的时 units.txt 会存在相同的前缀
使用decode_single_token_bytes， 然后再转成字符串
=> [whisper] fix convert_to_wenet_units

wenet/bin/train.py, wenet/utils/executor.py, wenet/utils/train_utils.py
1. wenet 2.2.1 中 configs['step']从-1开始而不是0开始 https://github.com/wenet-e2e/wenet/blob/v2.2.1/wenet/bin/train.py#L223 
2. wenet 2.2.1 中 self.step只有在accum_grad处才+1 https://github.com/wenet-e2e/wenet/blob/v2.2.1/wenet/utils/executor.py#L109  (上述不同应该不影响训练结果（或者说影响不大）。configs['step'] 对学习率影响只有一步之差。 self.step纯用来打印log，不影响训练流程)
3. `dist.barrier()` 移动到 `new_group` 之前，强制同步，减少超时出现的频率
4. 增加 `destroy_process_group`，对已经完成使命的`group_join`进行析构，避免 超过 `ulimit -u` 中限制的 `max user processes` https://github.com/google/jax/issues/2685
```sh
Root Cause (first observed failure):
[0]:
time      : 2023-11-28_05:28:31
host      : hobot-job-10017872-task-1.hobot-job-10017872.project-2080ti-speech-smalltask.svc.cluster.local.
rank      : 0 (local_rank: 0)
exitcode  : 1 (pid: 1554)
error_file: …
```
=> fix(train): Fix step & destroy group

examples/vkw2021/s0/local/vkw_kws_results.py, test/wenet/text/test_parallel.py, tools/onnx2horizonbin.py, wenet/bin/alignment.py, wenet/bin/recognize_onnx_gpu.py, wenet/text/bpe_tokenizer.py, wenet/text/whisper_tokenizer.py
after https://github.com/wenet-e2e/wenet/pull/2165 :
NOTE: 这几个文件只是兼容了下新的tokenizer和Dataset的接口，具体有些char dict到字的生成逻辑保持原有，之后有时间再修正（用tokenizer.detokenize or id2tokens）
=> [text] fix whisper tokens and others

wenet/transformer/search.py
fix https://github.com/wenet-e2e/wenet/issues/2181
conformer 没有 r_decoder, 默认的 run,sh reverse_weight > 0, 所以触发2181的bug
=> fix(decode): conformer without r_decoder

test/wenet/text/test_hugging_face_tokenizer.py, test/wenet/text/test_parallel.py, wenet/text/base_tokenizer.py, wenet/text/hugging_face_tokenizer.py
For llm, hugface is much more popular
this pr
next pr
=> [text] huggingface tokenizer

wenet/transformer/asr_model.py, wenet/transformer/search.py, wenet/whisper/whisper.py
whisper-large-v3 finetuned on aishell
=> feat(whisper): Support whisper-style decoding

examples/librispeech/rnnt/conf/conformer_rnnt.yaml, examples/librispeech/rnnt/run.sh, examples/librispeech/s0/conf/train_conformer.yaml, examples/librispeech/s0/conf/train_conformer_bidecoder_large.yaml, examples/librispeech/s0/conf/train_squeezeformer.yaml, examples/librispeech/s0/conf/train_squeezeformer_bidecoder_large.yaml, examples/librispeech/s0/conf/train_u2++_branchformer.yaml, examples/librispeech/s0/conf/train_u2++_conformer.yaml, examples/librispeech/s0/conf/train_u2++_efficonformer_v1.yaml, examples/librispeech/s0/conf/train_u2++_efficonformer_v2.yaml, examples/librispeech/s0/conf/train_u2++_squeezeformer.yaml, examples/librispeech/s0/conf/train_unified_conformer.yaml, examples/librispeech/s0/run.sh
follow https://github.com/wenet-e2e/wenet/pull/2205
=> [recipe] refine yaml for librispeech

examples/wenetspeech/s0/conf/train_conformer.yaml, examples/wenetspeech/s0/conf/train_conformer_bidecoder.yaml, examples/wenetspeech/s0/run.sh
=> [recipe] refine yaml for wenetspeech

examples/librispeech/s0/run.sh
替换下划线的操作 在新的 `bpe_tokenizer.py` 中实现了，https://github.com/wenet-e2e/wenet/blob/main/wenet/text/bpe_tokenizer.py#L51  ， 所以这里run.sh 不需要这个后处理，否则最终结果所有单词全都连到一块了
=> [examples] fix bug for bpe decoding

examples/aishell4/s0/conf/train_conformer.yaml, examples/aishell4/s0/run.sh
=> [recipe] refine yaml for aishell4

wenet/bin/average_model.py, wenet/bin/train.py, wenet/utils/executor.py, wenet/utils/train_utils.py
fix https://github.com/wenet-e2e/wenet/issues/1839
=> [bin] support model saving for both per-step & per-epoch mode

wenet/bin/train.py, wenet/utils/train_utils.py
1. finetune load previous ckpt时，如果检查点是step_xxx则step+1，如果检查点是epoch_xxx则epcoh + 1
2. `wenet/bin/train.py` 中 已经对 group 设定了timeout，这里无需再设
=> [train] fix bug of timeout and step

examples/wenetspeech/s0/README.md, examples/wenetspeech/s0/run.sh, wenet/bin/recognize.py, wenet/transformer/asr_model.py
The "blankpenalty" can mitigate deletion errors and is highly effective when the number of deletion errors in the recognition results is close to or even exceeds the number of substitution errors.
Detailed explanation (in chinese): https://e2qq6pi6j9.feishu.cn/docx/EFpod2n30omXITx08OAcMSjlnxd
results on wenetspeech (u2pp trained):
=> [decode] blank penalty

test/wenet/text/test_paraformer_tokenizer.py, wenet/cli/paraformer_model.py, wenet/paraformer/cif.py, wenet/paraformer/convert_paraformer_to_wenet_config_and_ckpt.py, wenet/paraformer/paraformer.py, wenet/paraformer/search.py, wenet/utils/init_model.py
related issues:
1 https://github.com/wenet-e2e/wenet/issues/2273
2 https://github.com/wenet-e2e/wenet/issues/2069#issuecomment-1786276989
=> [paraformer] timestamp

test/wenet/paraformer/test_paraformer.py, wenet/paraformer/attention.py, wenet/paraformer/convert_paraformer_to_wenet_config_and_ckpt.py, wenet/paraformer/embedding.py, wenet/paraformer/layers.py, wenet/paraformer/paraformer.py, wenet/paraformer/subsampling.py, wenet/transformer/encoder.py, wenet/utils/class_utils.py, wenet/utils/train_utils.py
重构encoder 支持wenet/transformer/encoder's dynamic chunk training
0 为什么要支持paraformer mask training？
尝试使用pretrain的非流paraformer，fintune训练u2++ like的流式模型，看是否可以得到好的效果
- ctc for streaming
- cif + paraformer decoder for two-pass rescoring
1 为什么要有：IdentitySubsampling？ 
因为wenet顺序是： cmvn->subsampling->pos emb
paraformer 顺序是： lfr(subsampling) ->cmvn -> pos_emb
所以这里实现了个IdentitySubsampling， 什么也不做,只是调用了pos emb class，保持接口不变
2 paraformer fsm block中有padding， 可能对流式训练有影响（训练和推理chunk不一致）
TODO 
example: 
ctc_weight: 0.3
use_dynamic_chunk: true
=> [paraformer] support chunk mask

wenet/bin/average_model.py, wenet/ctl_model/asr_model_ctl.py, wenet/utils/init_tokenizer.py
format file via `pre-commit run --all-files`
=> [lint] format files

wenet/transformer/ctc.py
- https://pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html
- zero_infinity (bool, optional) – Whether to zero infinite losses and the associated gradients. Default: False Infinite losses mainly occur when the inputs are too short to be aligned to the targets.
Setting `zero_infinity=True` can help us save a lot of time in data cleaning, as unclean data can be invalidated in the loss calculation through this flag.
=> [loss] set zero_infinity=True to ignore NaN or inf ctc_loss

wenet/dataset/processor.py
when tarfile open failed, stream will cause "UnboundLocalError: local variable 'stream' referenced before assignment"
=> [dataset] fix stream is none

examples/aishell/whisper/README.md, examples/aishell/whisper/conf/finetune_whisper_largev3_conv2d4_onlyattn.yaml, examples/aishell/whisper/conf/finetune_whisper_largev3_onlyattn.yaml
Fine-tuning the Whisper-large-v3 in pure-attention mode yielded better results (even if we use 1/4 subsample) compared to Yuekai's recipe:  https://github.com/k2-fsa/icefall/pull/1466
=> [examples] update whisper results on aishell-1

examples/aishell/whisper/README.md, examples/aishell/whisper/conf/ds_stage1.json, examples/aishell/whisper/conf/finetune_whisper_largev3.yaml, examples/aishell/whisper/conf/finetune_whisper_largev3_conv2d4.yaml, examples/aishell/whisper/local/modify_ckpt.py, examples/aishell/whisper/run.sh
1. Initializing the `ctc.ctc_lo.weight` with the `decoder.embed.0.weight` enhances convergence.
2. zero dp, 0.1 -> 0.0
3. smaller lr, 5e-4 -> 1e-5
4. larger epochs, 40 -> 80
5. more updates, accum 4 -> accum 1
=> [examples] update whisper results on aishell

examples/aishell/paraformer/README.md, examples/aishell/paraformer/conf/train_paraformer.yaml, examples/aishell/paraformer/conf/train_paraformer_dynamic.yaml, examples/aishell/paraformer/run.sh
1. initializing `ctc.ctc_lo.weight` and `embed.0.weight` (used in sampler) with `decoder.embed.0.weight`
2. zero dp, 0.1 -> 0.0
3. larger epochs, 45 -> 60
=> [examples] update paraformer results on aishell

test/wenet/dataset/test_datapipes.py, wenet/dataset/datapipes.py, wenet/dataset/dataset.py, wenet/dataset/processor.py
follow this pr https://github.com/wenet-e2e/wenet/pull/2316
TODO:
=> [dataset] support bucket by seq length

requirements.txt, test/wenet/dataset/test_datapipes.py, test/wenet/whisper/test_whisper.py, wenet/bin/recognize.py, wenet/dataset/dataset.py, wenet/dataset/processor.py, wenet/paraformer/paraformer.py, wenet/transformer/asr_model.py, wenet/transformer/search.py, wenet/utils/common.py, wenet/whisper/whisper.py
use https://github.com/saffsd/langid.py to detect language on the fly.
results look good:
```py
import langid
print(langid.classify("Questo è un testo di prova."))
print(langid.classify("hello world"))
print(langid.classify("中国北京天安门"))
print(langid.classify("使用GPS进行定位"))
print(langid.classify("Hi, 你好"))
```
```sh
('it', -95.88065242767334)
('en', -23.719746112823486)                                                                                                                                                                                                          ('zh', -90.74214363098145)
('zh', -78.27495694160461)
('zh', -35.134679317474365)
```
langid could detect most of the common languages.
```py
from whisper.tokenizer import LANGUAGES as WhiserLanguages
WHISPER_LANGS = …
```
=> [whisper] support arbitrary language and task

.github/workflows/unit_test.yml, test/wenet/ssl/w2vbert/test_w2vbert.py, wenet/dataset/processor.py
https://github.com/wenet-e2e/wenet/issues/2305
w2vbert facebook 开源了600M 模型， 在4.5M 小时上预训练
w2vbert 分四部分pr， 
future pr
=> [w2vbert] support w2vbert fbank

test/wenet/transformer/test_attention.py, wenet/transformer/attention.py, wenet/transformer/encoder.py
follow this pr: https://github.com/wenet-e2e/wenet/pull/2351
参考：https://github.com/facebookresearch/fairseq2/pull/142
TODO
=> [conformer] support flash att by torch sdpa

runtime/core/decoder/ctc_wfst_beam_search.cc, runtime/core/decoder/ctc_wfst_beam_search.h, runtime/core/decoder/params.h, runtime/core/utils/string.cc
Following https://github.com/wenet-e2e/wenet/pull/2320 which makes feature extraction pipeline compatible with whisper. We realized blank token idx is hard coded https://github.com/wenet-e2e/wenet/issues/2329, resulting in weird decoding results in the previous PR.
This PR is aiming at fixing that. **There might be some places that i missed, can you folks help me do another pass?**
Current RTF is 2.xx after warming up,  using one core with beam size of 8, on my local macbook. I think the model is probably capable of running at real time with avx512 on multiple cores, even with whisper large. so let's get it to work!
However, there is still some loose ends. Maybe you guys already know the answer and can share some insights.
- decoder main result **still slightly differs from …
=> [runtime] Configurable blank token idx

examples/wenetspeech/s0/README.md, examples/wenetspeech/s0/conf/train_u2++_conformer.yaml, examples/wenetspeech/s0/run.sh, examples/wenetspeech/whisper/README.md
:warning:**quality is important than quantity**:warning:
see https://github.com/wenet-e2e/WenetSpeech/discussions/54 for more infos
|   Model   |  Dev | Test\_Net | Test\_Meeting | blankpenalty |                                                                                                                  
|:-------------------:|:----:|:---------:|:-------------:|:-----------:|
|  u2pp_conformer (original transcripts) | 8.37 % N=328207 C=302993 S=12556 D=12658 I=2253  |   9.02 % N=414285 C=379271 S=23881 D=11133 I=2365     |     15.52 % N=220358 C=187746 S=14507 D=18105 I=1596     | 0.0 |
|  -  | 7.10 % N=328207 C=308457 S=13211 D=6539 I=3537  |   8.83 % N=414285 C=381933 S=24810 D=7542 I=4215     |     13.63 % N=220358 C=194446 S=16232 D=9680 I=4132     | 2.5 |
|  u2pp_conformer …
=> [examples] better results on wenetspeech using revised transcripts

wenet/transformer/search.py, wenet/whisper/whisper.py
原生whisper在wenet上解码时，有的不会停止， encoder_out 的size 作为maxlen 会超过 decoder embed的max len
wav/test/S0915/BAC009S0915W0303.wav
修改后正确解码：
```bash
2024-03-04 13:29:56,745 INFO attention wav/test/S0915/BAC009S0915W0303.wav 今后所有空调产品还将实现联机运行
```
=> [whisper] fix decoding maxlen

wenet/transformer/attention.py, wenet/transformer/decoder.py, wenet/transformer/decoder_layer.py, wenet/transformer/search.py, wenet/utils/class_utils.py
=> [transformer] add cross attention

wenet/transformer/attention.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py, wenet/transformer/positionwise_feed_forward.py
https://github.com/wenet-e2e/wenet/pull/2363#issuecomment-1961189853 
- asr bias会影响性能
- 预训练（speech pretrain and llm ） 会选择性关闭部分bias
该pr 支持三种bias
- q k v bias (llm)
- mlp bias (llm)
- conformer 的conv 的bias （w2vbert2 and llm）
=> [transformer] support bias

wenet/transformer/decoder.py, wenet/transformer/encoder.py, wenet/transformer/positionwise_feed_forward.py, wenet/utils/class_utils.py
gated mlp  是llm重要部分，在asr上也有提升参考这个https://github.com/wenet-e2e/wenet/pull/2363#issuecomment-1961189853
=> [transformer] add gated mlp

wenet/transformer/convolution.py, wenet/transformer/decoder.py, wenet/transformer/decoder_layer.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py
eps 会影响性能， llm通常使用1e-6，torch默认是1e-5  asr 也有影响 https://github.com/wenet-e2e/wenet/pull/2363#issuecomment-1961189853
=> [transformer] add norm eps

wenet/transformer/search.py
According to: 
https://github.com/wenet-e2e/wenet/blob/a93af33afb29585d7398265f1076d6dec1f11ab8/runtime/core/decoder/ctc_prefix_beam_search.cc#L142
=> [ctc] Update search.py

test/wenet/transformer/test_attention.py, wenet/dataset/processor.py, wenet/ssl/w2vbert/convert_w2vbert_to_wenet_config_and_ckpt.py, wenet/transformer/attention.py, wenet/transformer/subsampling.py, wenet/utils/class_utils.py
https://github.com/wenet-e2e/wenet/issues/2305
meta开源的w2vbert2.0 的权重是在4Mh的数据上pretrain训练（支持流式）， 模型是conformer，大小600M，  输入是fbank
diff 只有三处
其他实现均一致， 
此次迁移，有潜在三大收益
- whisper 可做对比 以及嫁接模型等 多了fintune选择
-  目前speech+llm 大部分方案，采用了whisper encoder， 大小和该encoder 一致，  给未来speech+llm 提供其他选择
- wenet ssl/本身支持w2vbert的pretrain， 此次迁移相当于wenet 也有了预训练模型， 有了更多的可能性（比如使用基于wenet 快速构建情绪emb的预训练模型、continue pretrain on 业务数据 etc）
https://twitter.com/reach_vb/status/1750225679898071232
该pr TODO：
之后prTODO：
=> [ssl/w2vbert] weight copy from meta w2vbert-2.0

wenet/transformer/attention.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py
muitl query 可以减少cache占用，加快解码速度， llm中slm中会用到 比如gemma等
并且根据paper https://github.com/wenet-e2e/wenet/pull/2363#issuecomment-1961189853， 我们可以在multihead 训练的模型基础上， 用MQA 继续训练 
ASR上 https://github.com/wenet-e2e/wenet/pull/2363#issuecomment-1961189853， 中显示 确实可以和multihead 达到一致的性能
=> [transformer] support multi query attention && multi goruped

wenet/transformer/search.py
after line441, `score` has become a tensor instead of a scalar.
=> [search] Update search.py

examples/aishell/whisper/local/modify_ckpt.py, wenet/transformer/search.py
A bug was introduced in https://github.com/wenet-e2e/wenet/pull/2381, basically it will skip copying all the weight if remove_list is empty.
=> Fix ckpt conversion bug

wenet/bin/recognize.py
=> [wenet/bin/recognize.py] modify args to be consistent with train

wenet/transformer/embedding.py
```python
48行： self.pe = torch.zeros(self.max_len, self.d_model)
模型初始化的时候，这个成员在cpu上
73行：self.pe = self.pe.to(x.device)
``` 
fsd的时候， self.pe 被注册为cpu, 等号不能成立，报错
=> [transformer] remove pe to device

wenet/bin/train.py, wenet/utils/common.py, wenet/utils/executor.py, wenet/utils/train_utils.py
=> add timer for steps

wenet/transformer/attention.py, wenet/utils/common.py
=> [transformer] fix sdpa u2pp training nan

tools/compute_cmvn_stats.py, tools/compute_fbank_feats.py, tools/wav2dur.py
在torchaudio>2.0版本中移除了全局backend选项，采用在函数调用中backend参数指定后端，并将默认的backend设为ffmpeg
> In 2.0, audio I/O backend dispatcher was introduced. Users can opt-in to using dispatcher by setting the environment variable TORCHAUDIO_USE_BACKEND_DISPATCHER=1.
> 
> In 2.1, the disptcher became the default mechanism for I/O.
> 
> In 2.2, the legacy global backend mechanism is removed. Utility functions get_audio_backend() and set_audio_backend() became no-op.
参考：[TorchAudio Dispatcher Migration](https://github.com/pytorch/audio/issues/2950)
=> [torchaudio] Fix torchaudio interface error (#2352)

wenet/dataset/dataset.py, wenet/dataset/processor.py
当shard/raw list中存在多通道数据，dataset会在padding部分报错，错误信息如下(or 类似)
```
padded_wavs = pad_sequence(sorted_wavs, batch_first=True, padding_value=0)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/utils/rnn.py", line 399, in pad_sequence
return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
RuntimeError: The size of tensor a (2) must match the size of tensor b (26645) at non-singleton dimension 1
```
This pr tries to fix the above problem
=> [dataset] add singal channel conf & processor

runtime/core/post_processor/CMakeLists.txt, runtime/ipex/CMakeLists.txt, runtime/libtorch/CMakeLists.txt
In the original version, it didn't work without itn.  but now a further separation of references 'wetext' can ensure that it works without itn.
=> [runtime] Fixed failed compilation without ITN. Now, compiling ITN is mandatory.

runtime/core/decoder/ctc_endpoint.cc, runtime/core/decoder/ctc_endpoint.h, runtime/core/decoder/params.h
same with ctc_log_probs in asr_decoder.cc
=> [runtime] add blank_sacle in ctc_endpoint

wenet/transformer/attention.py, wenet/transformer/embedding.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py, wenet/utils/class_utils.py, wenet/utils/rope_utils.py
https://github.com/wenet-e2e/wenet/pull/2363
TODO:
BTW:  目前实现不支持transformer decoder+rope 
- decoder + rope 性能会降低
- llm 大多是为decoder only架构， 不需要cross att 的cache
=> [transformer] add rope for transformer/conformer

wenet/bin/train.py, wenet/utils/checkpoint.py, wenet/utils/executor.py, wenet/utils/fsdp_utils.py, wenet/utils/train_utils.py
torch fsdp to support large speech model  or llm
与fsdp相关的pr
-  https://github.com/wenet-e2e/wenet/pull/2431
-  https://github.com/wenet-e2e/wenet/pull/2413
-  https://github.com/wenet-e2e/wenet/pull/2428
-  https://github.com/wenet-e2e/wenet/pull/2411
-  https://github.com/wenet-e2e/wenet/pull/2437
- https://github.com/wenet-e2e/wenet/pull/2449
=> [train_engine] support fsdp

wenet/bin/recognize.py, wenet/bin/train.py, wenet/finetune/lora/attention.py, wenet/finetune/lora/encoder.py, wenet/finetune/lora/layers.py, wenet/finetune/lora/utils.py, wenet/utils/init_model.py, wenet/utils/train_utils.py
LoRA support
references:
https://github.com/microsoft/LoRA/tree/bugfix_MergedLinear
https://kexue.fm/archives/9590
https://github.com/huggingface/peft
Qlora(better for memory cost): https://arxiv.org/pdf/2305.14314.pdf
(I think PEFT methods used in NLP all have the potential to tune the ASR model)
LoRA experiment:
gpus: 4*3090
lora_list in encoder
| base_model | finetune_mathod | lora_rank | lora_alpha | lora_dropout | lora_list | decoding mode             | test-aishell CER   | wenetspeech-test-net CER   | num of parameters | time/per-epoch | gpu mem |
| -------- | -------- | --- | --- | --- | --- | --------------------------- | ------- | ------- | ------- | ------- | ------- |
| wenet_u2pp_conformer(wenetspeech) | baseline | / | / | / | / | attention rescoring       | 5.83% | 10.82 % | …
=> LoRA support

README.md, requirements.txt, tools/compute_cmvn_stats.py, tools/wav2dur.py, wenet/dataset/dataset.py, wenet/dataset/processor.py, wenet/finetune/lora/attention.py, wenet/finetune/lora/encoder.py, wenet/finetune/lora/layers.py, wenet/finetune/lora/utils.py
3.8 是torch2.x支持的最低版本，未来随时可能会停止支持，所以升级一下
=> [env] update python version and deepspeed version

wenet/bin/train.py, wenet/utils/checkpoint.py, wenet/utils/common.py, wenet/utils/executor.py, wenet/utils/scheduler.py, wenet/utils/train_utils.py
当微调的时候，模型的不同部分需要的学习率和warmup不一样,比如以下 微调whisper的手 因为没有ctc的weight
我门可以设置ctc的warmu up为12000， lr 0.01， 其他部分为1200,0.00001
```yaml
optim: adam
optim_conf:
lr: [0.01, 0.00001]
modules: ['ctc']
scheduler: warmuplr
scheduler_conf:
warmup_steps: [1500,5000]
```
=> [transformer] add multi warmup and learning rate for different modules

examples/aishell/s0/conf/train_u2++_branchformer.yaml, examples/librispeech/s0/conf/train_u2++_branchformer.yaml, wenet/branchformer/encoder.py, wenet/branchformer/encoder_layer.py
=> [branchformer] simplified branchformer

test/wenet/transformer/test_attention.py, test/wenet/whisper/test_whisper.py, wenet/branchformer/encoder_layer.py, wenet/e_branchformer/encoder_layer.py, wenet/transformer/attention.py, wenet/transformer/decoder.py, wenet/transformer/decoder_layer.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py
TODO:
QA:
- torch.cat 和torch.split 在attention里边没有必要
- LLM 的实现， 会把 k v cache 先申请max_len的， 然后tuple（k_cache, v_cache）, 在attention 里边去写 copy （去写最一开始申请好的）
详细见：
- https://github.com/google/gemma_pytorch/blob/main/gemma/model.py#L268-#L264
- https://github.com/meta-llama/llama/blob/main/llama/model.py#L236-#L286
- 避免到处同样的代码，
-  为将来支持LLM
- jit /onnx 导出， forward_chunk 接口含义不变 (不影响jit 和onnx etc)
=> [transformer] refactor cache

wenet/paraformer/layers.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py
According to pytorch API: https://pytorch.org/docs/stable/checkpoint.html
It is recommended to use `use_reentrant=False`.
=> [transformer] set use_reentrant=False for gradient ckpt

wenet/ctl_model/asr_model_ctl.py, wenet/k2/model.py, wenet/paraformer/layers.py, wenet/paraformer/paraformer.py, wenet/ssl/w2vbert/w2vbert_model.py, wenet/ssl/wav2vec2/wav2vec2_model.py, wenet/transformer/asr_model.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py
=> [transformer] fix warning: ignore(True) has been deprecated

wenet/paraformer/layers.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py, wenet/utils/checkpoint.py, wenet/utils/init_model.py
=> [log] avoid reduntant logging

wenet/transformer/attention.py
1 消除重复代码
2 mqa的时候 head==1， 利用广播，不需要repeat， mga采用repeat
=> [transformer] refactor mqa repeat

runtime/core/bin/websocket_client_main.cc, runtime/core/websocket/websocket_client.h
Wenet previously only supported 16K.
I want to apply this to the call center and needed support for 8k.
I modified part of the code from websocket_client
The code was changed to allow 8k audio to be decoded using the --sr parameter.
You can decode 8k audio by modifying the code below.
./build/bin/websocket_client_main \
--hostname x.x.x.x --port xxxxx \
--sr 8000 \
--wav_path $wav_path 2>&1 | tee client.log
@Mddct could you check this modification ?
=> [websocket] 8k and 16k support

test/wenet/dataset/test_datapipes.py, test/wenet/dataset/test_dataset.py, tools/compute_cmvn_stats.py, wenet/bin/recognize.py, wenet/utils/train_utils.py
**Fix #2506**
**P.S.** The indentation adjustment of the code is to pass the format check of yapf.
=> [Fix #2506] Specify multiprocessing context in DataLoader

wenet/transformer/encoder.py, wenet/utils/mask.py
`max_chunk_size` is hard code to 25 (1s, 1/4 subsample), this PR makes it configurabal
=> [mask] set max_chunk_size according to subsample rate

test/wenet/dataset/test_datapipes.py, test/wenet/dataset/test_dataset.py, tools/compute_cmvn_stats.py, wenet/bin/recognize.py, wenet/utils/train_utils.py
I have to revert this PR wenet-e2e/wenet#2507 , I cannot laungh deepspeed engine after this PR.
Besides, the above PR is made to solve dataloader issue on KUNPENG CPU, but we have no plan to support it, I think users can hard code it if KUNPENG CPU is the must-one choice
=> Revert "[Fix #2506] Specify multiprocessing context in DataLoader"

wenet/transformer/attention.py
https://github.com/wenet-e2e/wenet/issues/2517
=> [transformer] try to fix mga in onnxruntime

wenet/utils/train_utils.py
when `accum_grad` is large, say 16, `steps/sec` might be less than 0.1
=> [utils] update precision of speed metric

wenet/dataset/processor.py
解决Kunpeng cpu上 segmentfault 的同时，避免了 deepspeed 的重复初始化。
只粗略定位到是数据集处理模块 processor.py 中存在多线程处理的操作，造成了多进程读取数据时的死锁问题。因此在 processor 开始处设置线程数为1，来防止死锁和 segmentfault
为防止侵入式修改，在读取 cpu 硬件信息判断为 Kunpeng 后才进行此修改。
- fix segmentfault in Kunpeng (#2506)
- avoids the repeated initialization of deepspeed causing by (#2507)
=> fix segmentfault in (#2506)

wenet/transducer/transducer.py
Error when jit exporting transducer with previous code
Found this forward func is not necessary for jit export (like transformer/asr_model.py, line 77 and 78)
=> unuse forward when jit exporting transducer

wenet/cli/paraformer_model.py, wenet/dataset/processor.py, wenet/paraformer/convert_paraformer_to_wenet_config_and_ckpt.py
The default window in the `Paraformer` frontend is `hamming`. We can find more details [here](https://github.com/modelscope/FunASR/blob/42479a68cb3b2a95338d6c27a3ac9a5e66c60405/funasr/frontends/wav_frontend.py#L134). However, the default window in `kaldi.fbank` is `povey`, as specified [here](https://pytorch.org/audio/stable/generated/torchaudio.compliance.kaldi.fbank.html#torchaudio.compliance.kaldi.fbank). This different window maybe a little mismatch. As mentioned in line 44 of [this document](https://kaldi-asr.org/doc/feature-window_8h_source.html):
> "povey" is a window I made to be similar to Hamming but to go to zero at the edges, it's pow((0.5 - 0.5cos(n/N2*pi)), 0.85) I just don't think the Hamming window makes sense as a windowing function.
=> Using hamming window for Paraformer frontend.

runtime/gpu/model_repo/scoring/1/model.py, runtime/gpu/model_repo_stateful/wenet/1/wenet_onnx_model.py, wenet/bin/export_onnx_gpu.py, wenet/bin/recognize_onnx_gpu.py
fix eos sos to depending on dict or config
=> fix gpu-onnx infer

wenet/dataset/processor.py, wenet/ssl/bestrq/bestrq_model.py, wenet/ssl/init_dataset.py
=> [ssl] fix bestrq  l2norm

tools/compute_shard_cmvn_stats.py, tools/extract_shard_data.py
新增两个tools脚本：
分别用于从shard data.list中提取文本或者统计音频时长；使用shard data.list计算cmvn
为什么需要这个？有时只有shard格式的数据，而没有原始数据，但是需要计算cmvn和提取text
```bash
用法：计算音频时长
tools/extract_shard_data.py data/dev/data.list data/dev/wav.dura duration
用法：提取文本
tools/extract_shard_data.py data/dev/data.list data/dev/text text
用法：计算cmvn
tools/compute_shard_cmvn_stats.py \
--train_config conf/train_u2++_conformer.yaml \
--in_shard data/train/data.list \
--out_cmvn data/train/global_cmvn
```
=> [add] Use shard data to calculate cmvn and extract text

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [WeNet Guru](https://gurubase.io/g/wenet) to Gurubase. WeNet Guru uses the data from this repo and data from the [docs](https://wenet.org.cn/wenet/) to answer questions by leveraging the LLM.
In this PR, I showcased the "WeNet Guru", which highlights that WeNet now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to …
=> Introducing WeNet Guru on Gurubase.io

wenet/bin/export_onnx_gpu.py
https://github.com/wenet-e2e/wenet/issues/2653
https://github.com/wenet-e2e/wenet/issues/2635
=> [bin/export_gpu] fix streaming export onnx

wenet/__init__.py, wenet/cli/model.py, wenet/utils/init_model.py
For example, we can use it as
``` python
class SpeechLLM(nn.Module):
def __init__(self, encoder, llm):
self.encoder = encoder
self.llm = llm
def forward(self, speech, text, speech_len, text_len):
speech_emb = self.encoder.encoder.forward(speech, speech_lens)
text_emb = self.llm.get_input_embeddings()(text)
import wenet
speech_encoder = wenet.load_model_pt(xxx)
llm = Llama3()
speech = SpeechLLM(encoder=speech_encoder, llm=llm)
```
=> [cli] support on-the-fly training by loading pt model as nn.Module

wenet/firered/attention.py, wenet/firered/convert_FireRed_AED_L_to_wenet_config_and_ckpt.py, wenet/firered/encoder.py, wenet/firered/encoder_layer.py, wenet/firered/model.py, wenet/firered/subsampling.py, wenet/transformer/convolution.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py, wenet/utils/class_utils.py, wenet/utils/init_model.py
https://github.com/FireRedTeam/FireRedASR/tree/main  
目前Firred-LLM 没有release， 等release， 同步看下AED encoder 和LLM encoder区别 ，然后转过来
https://github.com/FireRedTeam/FireRedASR/issues/5#issuecomment-2636080535
=> [firred] bring fired aed to wenet

wenet/firered/attention.py, wenet/firered/model.py, wenet/firered/subsampling.py
=> [firred] jit works

wenet/firered/convert_FireRed_AED_L_to_wenet_config_and_ckpt.py
after： https://github.com/wenet-e2e/wenet/pull/2680
llm base的 https://huggingface.co/FireRedTeam/FireRedASR-LLM-L/tree/main 模型开源， 模型只是多了llm和projector部分， 该pr抽出enc， 可供west等项目使用
```bash
llm.base_model.model.model.layers.26.mlp.down_proj.lora_B.default.weight
llm.base_model.model.model.layers.27.self_attn.q_proj.lora_A.default.weight
llm.base_model.model.model.layers.27.self_attn.q_proj.lora_B.default.weight
llm.base_model.model.model.layers.27.self_attn.k_proj.lora_A.default.weight
llm.base_model.model.model.layers.27.self_attn.k_proj.lora_B.default.weight
llm.base_model.model.model.layers.27.self_attn.v_proj.lora_A.default.weight
llm.base_model.model.model.layers.27.self_attn.v_proj.lora_B.default.weight
llm.base_model.model.model.layers.27.self_attn.o_proj.lora_A.default.weight …
```
=> [firered] support enctor speech enc from llm base model

setup.py
jieba is required by punc model
yaml is required by load_model_pt
=> [cli] fix missing dependencies

.github/workflows/unit_test.yml
Update workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> [workflow] update workflow to use v3 of actions/cache
