examples/aishell/s0/run.sh, wenet/transformer/ctc.py
Change-Id: Ib96eb2705df4a11e7bcba6d4cddb8dbbf1bc5fee
=> [bugfix] fix optional parameter in run.sh and indent bug in ctc

.github/workflows/doc.yml, docs/.gitignore, docs/Makefile, docs/conf.py, docs/index.rst, docs/installation.md, docs/make.bat
=> [doc] add sphinx doc CI workflow

README.md, docs/jit_in_wenet.md
Change-Id: I2d21cba40d66c671c26a61373707b9f40f20f6d5
=> [doc] refine wenet readme

README.md, docs/index.rst
Change-Id: I6167be6b9fb2316edaf1c27c8bcb7e5c47b4714c
=> [doc] refine readme

.clang-format, runtime/server/x86/bin/BUILD, runtime/server/x86/bin/decoder_main.cc, runtime/server/x86/decoder/BUILD, runtime/server/x86/decoder/ctc_prefix_beam_search.cc, runtime/server/x86/decoder/ctc_prefix_beam_search.h, runtime/server/x86/decoder/ctc_prefix_beam_search_test.cc, runtime/server/x86/decoder/symbol_table.h, runtime/server/x86/decoder/torch_asr_decoder.cc, runtime/server/x86/decoder/torch_asr_decoder.h, runtime/server/x86/decoder/torch_asr_model.cc, runtime/server/x86/decoder/torch_asr_model.h, runtime/server/x86/frontend/BUILD, runtime/server/x86/frontend/fbank.h, runtime/server/x86/frontend/feature_pipeline.cc, runtime/server/x86/frontend/feature_pipeline.h, runtime/server/x86/frontend/fft.cc, runtime/server/x86/frontend/fft.h, runtime/server/x86/frontend/wav.h, runtime/server/x86/utils/BUILD, runtime/server/x86/utils/blocking_queue.h, runtime/server/x86/utils/utils.h
Change-Id: Id2f9c014b9683a85ef3c401f81cf5c1135f25f44
=> [runtime] refine runtime style

runtime/server/x86/CMakeLists.txt
Change-Id: Ib389f506c896c25d9df6b131b3741e057f0c0a0b
=> [runtime] support cmake compile

README.md
Change-Id: I6ba9b612b94d3c9b90ff331e335433fc11cf5073
=> [doc] remove kaldi dependency in readme

examples/aishell/s0/path.sh, tools/wav_to_duration.sh
Change-Id: I8d1823219a370dd4c0adc3778b04d69be691be2d
=> [fix] fix wav_to_duration bug and error info

examples/aishell/s0/README.md, examples/aishell/s0/conf/train_conformer.yaml, examples/aishell/s0/conf/train_unified_conformer.yaml, examples/aishell/s0/run.sh, wenet/transformer/convolution.py
Change-Id: Ic6a9821c2c41a20e96585b3561c23a48cffe1a53
=> [network] refine training parameter, change layernorm to batchnorm in conformer

examples/aishell/s0/README.md
Change-Id: Ieaa6d3816730524bd8d2ce35a55c1c61c35a8bea
=> [doc] add model link and model code version

README.md
Change-Id: I314d956757c970b616907c30ea3edb29da0bb04e
=> [doc] add wechat group QR code

examples/aishell/s0/conf/train_transformer.yaml
Change-Id: I7356ba72acea95d93bccc2e4f6eb7dcf4ab4dd5f
=> [conf] refine aishell train_transformer.yaml

examples/aishell/s0/README.md
Change-Id: I026dc596c01388b059526bbd4708ad984d5967e1
=> [doc] update aishell transformer result

examples/aishell/s0/conf/train_unified_transformer.yaml, examples/aishell/s0/run.sh
Change-Id: Ib8ae15bf48fe6429f556bd3c3ac559b36775128e
=> [conf] add unified transformer for aishell

examples/aishell/s0/README.md
Change-Id: I7ddf4200b0b89ddf72236a7441160945a394d1a4
=> [doc] update aishell unified transformer result

README.md
Change-Id: Ie675b060c852ca7e7a3a61914b13aa00c772428f
=> [doc] add personal qr code

runtime/device/android/wenet/README.md
Change-Id: I6ff5e6864ce540271337ea3a16b836c6bb1253f3
=> [doc] add android prebuilt apk

wenet/transformer/encoder.py
Change-Id: I13ced5714bf85082bd9e67c3fdf1c1f321fd2140
=> [fix] fix cmvn bug in conformer

runtime/device/android/wenet/README.md
Change-Id: I1cbd2ef5430ec57fb9974ff70c9789f70f30b246
=> [doc] update android app

examples/aishell/s0/README.md, examples/aishell/s0/conf/train_unified_conformer.yaml
Change-Id: I90fd32e1dd921449ef5b4d2db0a9d11fceb9c5e1
=> [doc] update u2 conformer on aishell

wenet/transformer/convolution.py
Change-Id: I2c399e5d82266505e3834472b2646b9758ee5891
=> [fix] fix conformer JIT export bug

examples/aishell/s0/README.md, examples/aishell/s0/conf/train_unified_transformer.yaml
Change-Id: Ica93b700a37df110867c28901809de9e3379ef04
=> [doc] update aishell u2 transformer

docs/index.rst, docs/papers.md, docs/runtime.md
Change-Id: I0970dd13b333d0c45b88a71107222f83b7138927
=> [doc] add papers

README.md
Change-Id: I79fd70fa86c19d2100fce97d45f563df5c969cf0
=> [doc] update readme

README.md
Change-Id: I9c611197f1e15741590f1a6b9384568c6012d7c1
=> [doc] add qr code backup link

tools/compute-wer.py, wenet/bin/recognize.py
[fix] add utf-8 encoding when open file
=> [fix] add utf-8 encoding when open file

tools/format_data.sh
stay the same with examples/multi_cn/s0/run.sh
=> [fix] change ch_char_en_bpe to cn_char_en_bpe

README.md, docs/tutorial.md
Change-Id: I4d12186e7a9f7b31294be09bae7fafadd8bda1c3
=> [doc] specify torchaudio version

requirements.txt, tools/compute_cmvn_stats.py, wenet/bin/alignment.py, wenet/bin/average_model.py, wenet/bin/export_jit.py, wenet/bin/recognize.py, wenet/bin/train.py, wenet/dataset/dataset.py, wenet/utils/checkpoint.py
=> fix pyyaml deprecated syntax

README.md, tools/compute_cmvn_stats.py, tools/wav2dur.py, wenet/dataset/dataset.py, wenet/dataset/wav_distortion.py
ref: [#243](https://github.com/mobvoi/wenet/pull/243)
=> fix bugs to support torchaudio==0.8.0

runtime/core/decoder/torch_asr_decoder.cc
when hyp num is zero , it will cause core dump , see below:
=> torch rescore empty tensor bug fix

runtime/core/bin/decoder_main.cc, runtime/core/bin/websocket_client_main.cc, runtime/core/decoder/torch_asr_decoder.cc, runtime/core/decoder/torch_asr_decoder.h, runtime/core/websocket/websocket_client.cc, runtime/core/websocket/websocket_client.h, runtime/core/websocket/websocket_server.cc, runtime/core/websocket/websocket_server.h
Change-Id: I40e21b39859c27ebb403765cafa352727cfd22d1
=> [runtime] support add continuous decoding

runtime/core/decoder/ctc_endpoint.h, runtime/core/decoder/torch_asr_decoder.cc
Change-Id: If35a8f00218346b42bf8cdd2f77e34d7ed8e44bf
=> [runtime] refine endpoint

runtime/core/utils/flags.h
Change-Id: I6f229b1676e33b66745ca8fcf72f9e546b744b35
=> [runtime] add flags.h

runtime/core/decoder/ctc_prefix_beam_search.h, runtime/core/decoder/torch_asr_decoder.h, runtime/core/decoder/torch_asr_model.h, runtime/core/utils/blocking_queue.h, runtime/core/utils/utils.h, runtime/core/websocket/websocket_client.h, runtime/core/websocket/websocket_server.h
Change-Id: I39fc3e4185e1f8191a249ac2b1a61b444cc013bf
=> [runtime] add wenet prefix for disallow copy and assign

runtime/server/x86/CMakeLists.txt
=> Revert "[runtime] add dependency"

README.md
Add aishell-2/mult_cn link in readme.md
=> [doc] Add aishell-2/mult_cn link in readme.md

tools/data/split_scp.pl, tools/fst/add_lex_disambig.pl, tools/fst/compile_lexicon_token_fst.sh, tools/fst/ctc_token_fst.py, tools/fst/ctc_token_fst_corrected.py, tools/fst/eps2disambig.pl, tools/fst/make_lexicon_fst.pl, tools/fst/make_tlg.sh, tools/fst/prepare_dict.py, tools/fst/remove_oovs.pl, tools/fst/rnnt_token_fst.py, tools/fst/s2eps.pl
Change-Id: I1b8083f4d2df3a1dd1b4b85a965a5d22969cdfba
=> [tools] add fst related tools

tools/decode.sh
Change-Id: I38bd4fca9cbe54fa9154bf4c424e2278daf43fab
=> [tools] add decode.sh

README.md
Change-Id: Id5d48b247be002071a3c6b23c6d9fa2e3ebb834c
=> [doc] add optional runtime build in readme

runtime/core/bin/decoder_main.cc
rtf on aishell2 test set is about 0.22 now
=> fix wave_dur calculation cast bug

examples/aishell/s0/README.md, examples/aishell/s0/kaldi_path.sh, examples/aishell/s0/local/aishell_train_lms.sh, examples/aishell/s0/path.sh, examples/aishell/s0/run.sh
Change-Id: I52c188edb19b140d6bfa2a626c36b44fe214f020
=> [examples] add aishell lm support

runtime/core/kaldi/CMakeLists.txt, runtime/server/x86/CMakeLists.txt
Change-Id: I7cd2d440c0eedc0619ba6381732bcadbbbff7b04
=> [runtime] fix linking error on linux

examples/aishell2/s0/kaldi_path.sh, examples/aishell2/s0/local/train_lms.sh, examples/aishell2/s0/path.sh, examples/aishell2/s0/run.sh
Change-Id: Id1b4a52ca3b0b00827cbfc7c01519430efc3aba9
=> [examples] remove kaldi dependency in aishell2

runtime/server/x86/README_CN.md
tar -xf http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell2/20210327_unified_transformer_exp_server.tar.gz
tar: 无法连接至 http: 解析失败
=> [doc] tar -xf 20210327_unified_transformer_exp_server.tar.gz

tools/compute_fbank_feats.py, wenet/dataset/kaldi_io.py
Change-Id: I8417068927ae19994a32bf2a9b0fd161585a7530
=> [tools] compute_fbank_feats works

tools/fst/make_tlg.sh, tools/fst/prepare_dict.py
Discussed in https://github.com/mobvoi/wenet/pull/360#discussion_r629787450
=> [examples] ignore oov word instead of replacing it with <unk>

runtime/core/bin/grpc_client_main.cc, runtime/core/bin/grpc_server_main.cc, runtime/core/grpc/grpc_client.cc, runtime/core/grpc/grpc_client.h, runtime/core/grpc/grpc_server.cc, runtime/core/grpc/grpc_server.h, runtime/core/grpc/wenet.proto
We only changed Ximalaya Inc to Ximalaya Speech Team in this pr
=> fix-ximalaya-corp-name

examples/aishell/s0/README.md, examples/aishell/s0/conf/train_conformer_no_pos.yaml, wenet/transformer/embedding.py, wenet/transformer/encoder.py, wenet/transformer/subsampling.py
Change-Id: Ib0f118e87d29f179fdbb03755fa218448acccbba
=> [network] add no position encoding support

wenet/transformer/subsampling.py
error annotation of `Conv2dSubsampling8`
=> fix error  annotation

examples/librispeech/s1/run.sh
The old script remove_longshortdata.sh has been removed. Update the receipe.
=> update librispeech receipe

wenet/transformer/encoder.py
see issue https://github.com/wenet-e2e/wenet/issues/388 for detail
=> handle a simulate forward chunk by chunk bug

wenet/transformer/asr_model.py, wenet/utils/common.py
Change-Id: I6af9baccb30f02423de7cde4140f20b033591536
=> [network] fix lint error

runtime/server/x86/CMakeLists.txt, runtime/server/x86/README.md, runtime/server/x86/README_CN.md
Change-Id: I4bf22bb7f8bdb9c2616539e6b2e059059e047683
=> [runtime] optional build with gRPC

examples/gigaspeech/s0/local/extract_meta.py, wenet/transformer/asr_model.py
Change-Id: Ia8332a01094cce17795337975be68c270029ffe6
=> [fix] fix lint

runtime/core/decoder/params.h, runtime/core/decoder/torch_asr_decoder.cc, runtime/core/decoder/torch_asr_decoder.h, runtime/core/websocket/websocket_server.cc, runtime/core/websocket/websocket_server.h, runtime/server/x86/CMakeLists.txt
Change-Id: I18677f7c22665c5f0439f3f158b6e3fc84a2a7e4
=> [runtime] convert StdVectorFst to Fst<StdArc>

runtime/server/x86/CMakeLists.txt
Change-Id: I5cb435e37108413f63cb882ea5824a9730823aa1
=> [runtime] fix dl link error

runtime/core/decoder/ctc_wfst_beam_search.cc, runtime/core/decoder/ctc_wfst_beam_search.h, runtime/core/kaldi/decoder/lattice-faster-decoder.cc
Change-Id: I36bea58a2443f54618f3a8d30b772ca22a194cad
=> [runtime] refine blank frame skipping

runtime/core/decoder/ctc_prefix_beam_search.h, runtime/core/decoder/torch_asr_decoder.cc, runtime/core/decoder/torch_asr_decoder.h, runtime/core/frontend/feature_pipeline.cc, runtime/core/frontend/feature_pipeline.h, runtime/core/kaldi/CMakeLists.txt, runtime/core/utils/utils.h, runtime/server/x86/docker/Dockerfile, wenet/transformer/attention.py, wenet/transformer/convolution.py, wenet/transformer/decoder_layer.py, wenet/transformer/encoder.py, wenet/transformer/encoder_layer.py
Refine comments for runtime and model code.
=> [doc] refine comments

README.md
Modified the bibtex information.
=> Modified the bibtex information.

runtime/core/decoder/params.h, tools/decode.sh
Change-Id: I7eaca04988176c20191601e2cb5237d612276b18
=> [runtime] support min-active parameter

runtime/core/decoder/torch_asr_decoder.cc
Change-Id: Ic092ca6efc98de039d7bb1eb4e93edee32fd7f5e
=> [runtime] fix no encoder output bug

runtime/core/bin/decoder_main.cc, runtime/core/decoder/torch_asr_decoder.cc, runtime/core/utils/string.cc, runtime/core/utils/string.h, runtime/core/utils/utils.cc, runtime/core/utils/utils.h, runtime/server/x86/CMakeLists.txt
Change-Id: If555ab4678d3087d59fb9bea042578df8e21979d
=> [runtime] move all str related function to string.h/string.cc

runtime/core/utils/utils.cc, runtime/core/utils/utils.h
Change-Id: Idcbaca4ce1d3be542187f18f77d7bcdfb18f1db5
=> [runtime] remove const and reference in LogAdd function

runtime/core/decoder/ctc_wfst_beam_search.cc, runtime/core/decoder/params.h
Change-Id: I762cd3655eb338ecfc73df2acf41fcabdd2f5435
=> [runtime] support nbest parameter in wfst decoding

runtime/core/decoder/ctc_wfst_beam_search.cc, runtime/core/decoder/ctc_wfst_beam_search.h, runtime/core/decoder/params.h, runtime/core/decoder/torch_asr_decoder.cc, runtime/core/decoder/torch_asr_decoder.h
Change-Id: Ic53232beb76fa96d2edb5d679ce7ea95f6c876b0
=> [runtime] support timestamp in wfst decoding

runtime/core/decoder/torch_asr_decoder.cc, runtime/core/decoder/torch_asr_decoder.h
Change-Id: I19782e2ee5d303bcda78306d44756d773ee5c9ff
=> [runtime] refactor postprocessing function

runtime/core/websocket/websocket_server.h
=> fix an error

wenet/transformer/subsampling.py
Change-Id: I764599c45a8b8135c85b243ae77eae11c003e78e
=> [network] fix right context error

runtime/core/bin/label_checker_main.cc, runtime/core/decoder/torch_asr_decoder.cc, runtime/core/frontend/wav.h, runtime/core/utils/string.cc, runtime/core/utils/string.h, runtime/server/x86/CMakeLists.txt
Change-Id: Ib1f5df4dba6b32439df6b5c2f6518e23664e45c0
=> [runtime] label checker works

wenet/bin/train.py
- so that the visual of lr is not affected by cv_loss
- and add close() for summarywritter
=> tensorboard: show fig of 'lr' and 'cv_loss' separately 

runtime/core/bin/grpc_server_main.cc, runtime/core/grpc/grpc_server.cc, runtime/core/grpc/grpc_server.h
use DecodeResource in grpc_server, fix the interface
=> fixed the new DecodeResource interface bug

wenet/bin/recognize.py
when recognizing wav, it's better to make dither = 0, and make the feats same as C++ result
In some cases, it will make result different.
=> wav_dither should be zero in eval

README.md
Change-Id: Iec0ff7502b9784e169f72623137c38404c7c92fc
=> [doc] replace google Groups with Github Discussions

runtime/device/android/wenet/app/src/main/cpp/wenet.cc
=> [fix(android)] init post_processor in android demo

wenet/utils/common.py
* [SiLU is shipped since pyTorch 1.7](https://pytorch.org/docs/stable/generated/torch.nn.SiLU.html)
* Use it as the swish implementation with backward compatibility
* Could improve speed slightly
=> use SiLU for swish under pyt19

wenet/dataset/processor.py
Change-Id: I3eba4b4b50cc3cb52fd56f62a4937189a97438db
=> [network] fix mutable parameter in speed_perturb

examples/aishell/s3/README.md
Change-Id: Ib4ec64f73ae72c54345e88edd4e61ac742076845
=> [doc] add raw io result for uio

runtime/core/post_processor/post_processor_test.cc, runtime/core/utils/string.cc, runtime/core/utils/string.h
Solution2 for issue https://github.com/wenet-e2e/wenet/issues/745
=> [runtime] lower/upper wstring

examples/librispeech/s0/run.sh
The dev set variable wasn't actually being used. The code was ignoring it, and just using the hard coded `dev` directory.
=> [examples] fix librispeech dev set variable usage

wenet/dataset/processor.py
Fixed subprocess residue in dataset process
=> Fixed subprocess residue in UIO

README.md, README_CN.md
fix issue https://github.com/wenet-e2e/wenet/issues/789
=> [doc] fix torchaudio version

wenet/dataset/processor.py
tar extractfile is file object, need to close
=> may fix unclose error

wenet/bin/average_model.py
wenet/bin/average_model.py cant get path_list in centos system.
=> fix bug that cant get path list in centos

runtime/core/frontend/feature_pipeline.cc
=> [runtime] fix issue#893, double check queue.empty in feature_pipeline

runtime/core/websocket/websocket_server.cc
- fix typo `Recieved` -> `Received`
- fix websocket crashes on connection close
=> websocket server: fix crashes due to websocket connection closes

wenet/bin/train_deprecated.py, wenet/utils/checkpoint.py
support loading pretrained encoders
=> support loading pretrained encoders

wenet/bin/recognize.py, wenet/bin/train.py, wenet/dataset/dataset.py, wenet/dataset/processor.py
1. UIO support mfcc features. 
2. train.py support loading pretrain encoders.
=> support mfcc features, support loading pretrain encoders.

wenet/bin/recognize.py
檔案 wenet/wenet/bin/recognize.py 
line:30 已經有實現的 read_symbol_table
line:124 已經讀取了 symbol_table
line:159:164 的目的 char_dict = (顛倒symbol_table的key, value)
因此可以簡化為我的commit
=> remove duplicated

examples/gigaspeech/s0/run.sh
=> Fix scripts

examples/openasr2021/s0/README.md
update readme and pre-train model link
=> update readme and pre-train model link

runtime/server/x86/README.md, runtime/server/x86/README_CN.md
=> [docs] update docker image

runtime/core/decoder/context_graph.cc
=> fix coredump when context empty

runtime/core/decoder/torch_asr_model.cc
fix num_left_chunks_ = other.num_left_chunks_;
=> fix num_left_chunks_ = other.num_left_chunks_;

runtime/core/bin/label_checker_main.cc
fix compile warning in MapToLabel
=> fix compile warning in MapToLabel

README_CN.md, docs/tutorial_aishell.md, examples/aishell/s0/run.sh, examples/aishell/s1/run.sh
add  faq in chinese readme for new user.
add comment for data variable in aishell run.sh
=> [doc] add faq for new user

runtime/core/decoder/asr_model.cc
remove unnesserary torch header
=> remove unnesserary torch header

wenet/bin/export_onnx_cpu.py
=> [bin] add doc for onnx export

wenet/transformer/asr_model.py
fix issue #1113 .
author: @Mddct
=> [model] refine reverse_pad_list

wenet/transformer/embedding.py
ref: https://github.com/pytorch/pytorch/issues/69434#issuecomment-1064306579
=> [fix] offset type check, separately

runtime/server/x86_gpu/README.md
Add a notice for streaming export
=> Update GPU README.md

runtime/core/decoder/asr_model.cc
watch this version as reference
https://github.com/wenet-e2e/wenet/blob/fd22df3a799568bf178258f6b1f576929e9bb43b/runtime/core/decoder/torch_asr_decoder.cc#L115
=> debug cache if

runtime/binding/python/py/decoder.py
set_context_score valid when context is not None
=> [binding/python] set_context_score

runtime/binding/python/README.md, runtime/binding/python/cpp/binding.cc, runtime/binding/python/py/decoder.py, runtime/core/api/wenet_api.cc, runtime/core/api/wenet_api.h
=> Revert "[binding]: add decode opts"

runtime/binding/python/py/decoder.py, runtime/binding/python/py/hub.py, runtime/binding/python/setup.py
=> [binding] download model auto

runtime/binding/python/py/hub.py
=> [binding] fix compress bug

runtime/core/frontend/feature_pipeline.cc, runtime/core/test/CMakeLists.txt, runtime/core/test/feature_pipeline_test.cc, runtime/core/utils/blocking_queue.h
Based on the previous discussion [PR#1252](https://github.com/wenet-e2e/wenet/pull/1252) ,I modified the `Push` and `Pop` functions,and `Read` of `feature_pipeline`.
=> [runtime] Optimize feats in pipeline

examples/aishell/rnnt/README.md
track the results of transducer not for merge now
=> [transducer] track aishell results

.gitignore, docs/tutorial_librispeech.md, examples/aishell/rnnt/run.sh, examples/aishell/s0/run.sh, examples/aishell/s0_deprecated/run.sh, examples/aishell/s1/run.sh, examples/aishell2/s0/run.sh, examples/aishell4/s0/run.sh, examples/chime4/s0/run.sh, examples/commonvoice/fr/run.sh, examples/csj/s0/run.sh, examples/hkust/s0/run.sh, examples/librispeech/s0/run.sh, examples/librispeech/s1/run.sh, examples/multi_cn/s0/run.sh, examples/openasr2021/s0/run.sh, examples/swbd/s0/run.sh, examples/tedlium3/s0/run.sh, examples/timit/run.sh, examples/vkw2021/s0/local/run_finetune_5h.sh, examples/vkw2021/s0/run.sh, examples/wsj/s0/run.sh, runtime/core/decoder/torch_asr_model.cc, tools/alignment.sh, wenet/transformer/convolution.py, wenet/transformer/embedding.py
fix *requried* -> *required* in codes and docs.
=> [*]: fix typo error

.github/workflows/doc.yml
Plz see: https://github.com/ryanfox/sphinx-markdown-tables/issues/36
=> [workflows] Fix markdown version of doc

wenet/transducer/predictor.py, wenet/utils/init_model.py
=> [transducer] conv predictor

runtime/OnnxRuntime/README.md
=> little update README.md

wenet/transducer/transducer.py
=> [transducer] hot fix, fix transducer weight

wenet/utils/scheduler.py
For fine-tuning it is better to have more regular warmup in configs
=> Allow zero warmup steps

wenet/bin/train.py
Currently if file exists it issues warning in the log
=> Delete file before update of symlink

examples/aishell/rnnt/README.md
=> [transducer] init rnnt from pretrained model

tools/analyze_dataset.py
cc @robin1001 @pengzhendong  @whiteshirt0429
=> feat(tools): Analyze dataset

tools/analyze_dataset.py
=> refactor(analyze): [cr_id_skip] Add trailing_sil and leading_sil

wenet/bin/export_onnx_cpu.py
=> refactor(onnx): [cr_id_skip] Export dynamic quantized onnx model

examples/aishell/s0/conf/train_u2++_conformer.yaml, examples/aishell/s0/conf/train_u2++_transformer.yaml, wenet/bin/recognize.py, wenet/bin/recognize_onnx.py, wenet/dataset/dataset.py, wenet/dataset/processor.py
conformer with spectrim, 80 ∼ 150ms latency reduction without any accuracy loss:
transformer with spectrim, 40~120ms latenct reduction with lower wer:
=> feat(rapid-u2++): [cr_id_skip] Add spectrim

tools/latency_metrics.py
Usage
```
python3 tools/latency_metrics.py \
--config ${config} \
--ckpt ${ckpt} \
--tag ${tag} \
--wavscp ${wavscp} \
--alignment ./ali_word_small.txt \
--chunk_size ${chunk_size} \
--font ${font_path} \
--dict ${dict_path} \
--result_dir ${result_dir} \
--gpu -1 \
--model_type transducer
```
E.g.
=> Latency metrics for rnn-t

tools/k2/make_hlg.sh
=> add icefall and k2 commit info

examples/librispeech/s0/README.md, examples/librispeech/s0/conf/train_squeezeformer_bidecoder_large.yaml, examples/librispeech/s0/conf/train_u2++_squeezeformer.yaml, wenet/squeezeformer/attention.py, wenet/squeezeformer/convolution.py, wenet/squeezeformer/encoder.py, wenet/squeezeformer/positionwise_feed_forward.py, wenet/squeezeformer/subsampling.py
> This PR is for fixing bugs on Squeezeformer
> 
> * Update
>   
>     
>    * [x]  enable reduce & recover multi times
>    * [x]  fix conflicts and bugs for jit export and streaming ASR
=> Squeezeformer[fix bugs]

tools/analyze_dataset.py
Results will be submitted to hugging face:
https://huggingface.co/datasets/wenet/Speech-Dataset-Analyze/tree/main
=> refactor(analyze_dataset): Support shard and raw

wenet/squeezeformer/encoder.py
ONNX 无法追踪torch.repeat_interleave算子
=> [squeezeformer] Support ONNX export.

runtime/horizonbpu/README.md
=> refactor(x3readme): Add sudo

runtime/gpu/Dockerfile/Dockerfile.server, runtime/gpu/README.md, runtime/gpu/model_repo/scoring/1/model.py, runtime/gpu/scripts/convert_start_server.sh
Upgrad triton image to latest version.
=> update docker image version for triton

wenet/ssl/bestrq/bestqr_model.py, wenet/ssl/bestrq/mask.py
[bestrq paper](https://arxiv.org/pdf/2202.01855.pdf)
[usm paper](https://arxiv.org/abs/2303.01037)
NOTE: only test encoder_type == 'conformer/transformer'
no benchmark for now
=> [ssl] bestrq support

tools/k2/prepare_mmi.sh
we should let prepare_char.py generate tokens.txt words.txt and lexicon.txt, rather than generate then in shell script
aishell units.txt is sorted, but It will cause bug when words are not sorted, it has already been verified by users from community
=> fix bug when word not sorted

wenet/ssl/bestrq/bestqr_model.py
from USM paper, multiple codebooks can stabilize training
=> [ssl] bestrq support multiple codebooks

examples/aishell/NST/run_nst.sh
Add `--dict_path` to decode.sh
=> Fix NST glitch

wenet/ssl/bestrq/bestqr_model.py
1 fix time stack position
2 fix mask in tail of utrance
=> [bestrq] fix time stack position

runtime/web/README.md, runtime/web/streaming_app.py
1. 100 audios are randomly generated to warm up the ASR model, otherwise the output will be stuck while speaking at first.
2. Text output is used as follows:
=> [runtime] support streaming ASR web demo

runtime/gpu/cuda_decoders/README.md, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/encoder/config_template.pbtxt, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/feature_extractor/1/model.py, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/feature_extractor/config_template.pbtxt, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/scoring/1/decoder.py, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/scoring/1/frame_reducer.py, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/scoring/1/model.py, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/scoring/1/wfst_decoding_config.yaml, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/scoring/config_template.pbtxt, runtime/gpu/cuda_decoders/model_repo_stateful_cuda_decoder/streaming_wenet/config_template.pbtxt, runtime/gpu/cuda_decoders/requirements.txt, runtime/gpu/cuda_decoders/run_streaming.sh, runtime/gpu/model_repo_stateful/wenet/config_template.pbtxt, runtime/gpu/scripts/run_qa.sh, runtime/gpu/tensorrt/run_streaming_small_model.sh, wenet/bin/export_onnx_gpu.py
This PR supports streaming gpu TLG decoding using https://pypi.org/project/riva-asrlib-decoder/0.4.0/ features.
=> [Ready] Add GPU Tlg streaming support

wenet/transducer/joint.py, wenet/transducer/transducer.py
1 support k2 rnnt loss training
2 support k2 latency delay
=> [transducer] support k2 rnnt loss and delay penality

tools/fst/prepare_dict.py
librispeech lexicon 前后变化：
aishell lexicon 前后变化：
=> fix(fst/dict): Fix issue #1923

wenet/paraformer/paraformer.py
=> [fix](paraformer): fix decoding bug for paraformer

runtime/core/bin/CMakeLists.txt
@robin1001 @xingchensong please help review, thanks!
=> [fix] update IPEX lib macro in CMake file

wenet/utils/common.py
修改了代码实现, 使其考虑time维度后可跟其他维度的情况的
=> [fix] 修复utils/common.py中pad_list未考虑time维度后可跟其他维度的情况(#2007)

wenet/transducer/joint.py
refer: https://arxiv.org/abs/2003.07705
future TODO:
=> [transducer] support hat transducer

runtime/binding/python/CMakeLists.txt
solve this issue: https://github.com/wenet-e2e/wenet/issues/2032
=> fix(wenetruntime): add ITN for python bingding

wenet/bin/recognize.py, wenet/transformer/asr_model.py, wenet/transformer/search.py
=> [transformer] unify decode results of all decoding methods

wenet/transformer/search.py, wenet/utils/common.py
we remove the context graph here, and will add it back in the following pr.
The code is almost aligned with it's counterpart in c++ runtime.
=> [transformer] refactor ctc prefix beam search

.github/workflows/lint.yml
fix https://github.com/wenet-e2e/wenet/pull/2084#issuecomment-1782274252
=> fix(lint): downgrade python version to pass flake8 lint

wenet/bin/alignment.py, wenet/cli/model.py, wenet/cli/transcribe.py, wenet/utils/ctc_utils.py
=> [cli] support alignment

wenet/utils/checkpoint.py
fix  https://github.com/wenet-e2e/wenet/pull/2055#issuecomment-1786270345
=> fix(utils): avoid GPU RAM surge when loading ckpt

wenet/cli/paraformer_model.py, wenet/paraformer/search.py
=> [paraformer] post process eos and @@

docs/python_package.md, wenet/cli/model.py, wenet/cli/paraformer_model.py, wenet/cli/transcribe.py
#2069 
Support gpu for cli. For jit cuda model, we may need several rounds of warmup to get acceleration.
=> support gpu for cli

wenet/bin/recognize.py
`init_model` API changed in https://github.com/wenet-e2e/wenet/pull/2055
=> fix(decode): fix recognize.py due to API change

examples/librispeech/s0/run.sh
1. remove init_method (use default env init for both single-node & multi-node)
2. some api changes related to https://github.com/wenet-e2e/wenet/pull/2055
=> fix(recipe): fix run.sh for librispeech

examples/aishell/NST/run_nst.sh, examples/aishell/paraformer/run.sh, examples/aishell/rnnt/run.sh, examples/aishell2/rnnt/run.sh, examples/aishell2/s0/run.sh, examples/aishell4/s0/run.sh, examples/commonvoice/fr/run.sh, examples/csj/s0/run.sh, examples/gigaspeech/s0/run.sh, examples/hkust/s0/run.sh, examples/multi_cn/s0/run.sh, examples/openasr2021/s0/run.sh, examples/swbd/s0/run.sh, examples/tedlium3/s0/run.sh, examples/timit/run.sh, examples/vkw2021/s0/run.sh, examples/wenetspeech/s0/run.sh, examples/wsj/s0/run.sh
follow https://github.com/wenet-e2e/wenet/pull/2108, I cannot give a test on those recipes but I think it's OK to have a quick fix in the future
=> fix(recipe): fix run.sh for all recipes

wenet/bin/recognize.py
https://github.com/wenet-e2e/wenet/pull/2106
=> [wenet ]recognize.py fix dataset returns dict

wenet/bin/recognize.py, wenet/paraformer/convert_paraformer_to_wenet_config.py, wenet/paraformer/export_jit.py
未来需要支持fintune的时候，再把init_paraofmer_model整合到init_model里边区， 目前是为了支持recognize.py(wav.scp)
=> [paraformer] support recognize.py

wenet/cli/model.py
fix https://github.com/wenet-e2e/wenet/issues/2126
=> [cli] fix bugs with uncertain output results

wenet/bin/recognize.py, wenet/paraformer/convert_paraformer_to_wenet_config.py, wenet/paraformer/export_jit.py, wenet/paraformer/layers.py, wenet/paraformer/paraformer.py, wenet/utils/init_ali_paraformer.py, wenet/utils/init_model.py
NOTE： 阿里 目前放出的模型 没有ctc, 所以没有 Intermediate ctc 其实可以用layer dorpout实现 但是 。目标是fintune 这个功能有没有都无所谓了 目前先不支持了
=> [paraformer] support fintune

wenet/utils/train_utils.py
=> refactor(train): move yaml saving to save_model()

runtime/web/app.py, runtime/web/requirements.txt
huggingface demo代码同步更新：https://huggingface.co/spaces/wenet/wenet_demo
=> [web] Update code from huggingface

setup.py
fix https://github.com/wenet-e2e/wenet/issues/2166
- `openai-whisper` for tokenizer
- `librosa` for computing feats
=> fix(cli): add requires for whisper

wenet/branchformer/cgmlp.py, wenet/e_branchformer/encoder.py, wenet/efficient_conformer/encoder.py, wenet/squeezeformer/encoder.py, wenet/transducer/joint.py, wenet/transducer/predictor.py, wenet/transformer/decoder.py, wenet/transformer/encoder.py, wenet/utils/class_utils.py
fix https://github.com/wenet-e2e/wenet/pull/2174#discussion_r1407285140
=> refactor(model): keep name pattern of class mapping

wenet/utils/class_utils.py
fix https://github.com/wenet-e2e/wenet/issues/2176
=> [paraformer]fix embed after wenet map class

wenet/whisper/convert_whisper_to_wenet_config_and_ckpt.py
fix https://github.com/wenet-e2e/wenet/issues/2171
=> fix(whisper): Disable speed_purterb

wenet/bin/recognize.py, wenet/transformer/asr_model.py, wenet/transformer/search.py, wenet/utils/ctc_utils.py, wenet/utils/train_utils.py
follow this PR https://github.com/wenet-e2e/wenet/pull/2157
=> feat(decode): support arbitrary blank_id during decoding

wenet/ctl_model/asr_model_ctl.py, wenet/k2/model.py, wenet/transducer/transducer.py
follow this PR: https://github.com/wenet-e2e/wenet/pull/2196
search methods need special tokens, it is better to hold them inside model.
=> refactor(model): Add special token to model

examples/aishell/rnnt/conf/conformer_rnnt.yaml, examples/aishell/rnnt/conf/conformer_u2pp_rnnt.yaml, examples/aishell/rnnt/conf/example_embedding_predictor.yaml, wenet/transducer/predictor.py, wenet/utils/init_model.py
去除init_model.py中一些冗余的赋值操作，转而在yaml中显式配置
=> [refactor] simplify code and keep API consisstent

examples/aishell/rnnt/run.sh, examples/aishell/s0/run.sh, examples/aishell2/rnnt/run.sh, examples/aishell2/s0/run.sh, examples/aishell4/s0/run.sh, examples/csj/s0/run.sh, examples/gigaspeech/s0/run.sh, examples/librispeech/rnnt/run.sh, examples/librispeech/s0/run.sh, examples/tedlium3/s0/run.sh, examples/vkw2021/s0/run.sh, examples/wenetspeech/s0/run.sh
本地开发机debug时可能没有八卡，此时需要手动修改CUDA_VISIBLE_DEVICES,不方便
=> [script] auto detect gpus

wenet/paraformer/convert_paraformer_to_wenet_config_and_ckpt.py
https://github.com/wenet-e2e/wenet/pull/2205#issue-2032081131, 引入了cmvn， 但是这里filter过滤掉了，fix下
nex pr
TODO:
=> [paraformer] fix cmvn files

examples/gigaspeech/s0/conf/train_conformer.yaml, examples/gigaspeech/s0/conf/train_conformer_bidecoder.yaml, examples/gigaspeech/s0/conf/train_u2++_conformer.yaml, examples/gigaspeech/s0/run.sh
=> [recipe] refine yaml for gigaspeech

examples/aishell2/s0/conf/train_u2++_conformer.yaml, examples/aishell2/s0/conf/train_u2++_transformer.yaml, examples/aishell2/s0/conf/train_unified_conformer.yaml, examples/aishell2/s0/conf/train_unified_transformer.yaml, examples/aishell2/s0/run.sh
=> [recipe] refine yaml for aishell2

examples/aishell2/rnnt/conf/conformer_rnnt.yaml, examples/aishell2/rnnt/conf/conformer_u2pp_rnnt.yaml, examples/aishell2/rnnt/run.sh, examples/aishell2/s0/conf/train_u2++_conformer.yaml, examples/aishell2/s0/conf/train_u2++_transformer.yaml, examples/aishell2/s0/conf/train_unified_conformer.yaml, examples/aishell2/s0/conf/train_unified_transformer.yaml, examples/aishell2/s0/run.sh
=> [example] refine yaml for aishell2-rnnt

wenet/dataset/processor.py
=> Revert "[dataset] change padding value to 0"

wenet/ctl_model/asr_model_ctl.py
Fix bug that descript in issue 2269, trainning error with `train_unified_conformer_ctl.yaml`.
=> Fix bug about issue#2269.

wenet/paraformer/paraformer.py, wenet/transformer/asr_model.py, wenet/utils/common.py
1 paraformer model is a subclass of ASRmodel
2 paraformer support ctc search
3 log print th_accuracy
full chunk
chunk_size=16
=> [paraformer] make paraformer is a subclass of ASRmodel

wenet/utils/train_utils.py
correct: 
grad_norm: 28.40692710876465
error: 
grad_norm: !!python/object/apply:torch._utils._rebuild_tensor_v2...
=> [wenet]fix the step_xx.yaml grad_norm issue

wenet/dataset/processor.py
before: The program crashed immediately when extracting shards_000002101.tar.
```py
import tarfile
files = ["shards_000002101.tar", "shards_000001369.tar"]
for f in files:
stream = tarfile.open(fileobj=open(f, "rb"), mode="r|*")
for tarinfo in stream:
with stream.extractfile(tarinfo) as file_obj:
try:
pass
except Exception as ex:
print("catch exception: {}".format(ex))
```
```sh
Traceback (most recent call last):
File "/jfs-hdfs/user/xingchen.song/workspace/github/wenet/examples/aishell/whisper/exp/test.py", line 13, in <module>
stream = tarfile.open(fileobj=open(f, "rb"), mode="r|*")
File "/bucket/output/jfs-hdfs/user/xingchen.song/tools/miniconda3/envs/py3.10-torch2.x/lib/python3.10/tarfile.py", line 1836, in open
t = cls(name, filemode, stream, **kwargs)
File …
```
=> [dataset] add try-except-finnaly for tar_file_and_group

.github/workflows/unit_test.yml, requirements.txt
https://github.com/microsoft/DeepSpeed/pull/4468 
新版本 deepspeed 有问题， 上游在修复中
=> fix deepspeed version

wenet/transducer/transducer.py
https://github.com/wenet-e2e/wenet/issues/2326
=> Fix loss returned by CTC model in RNNT

wenet/bin/average_model.py, wenet/utils/executor.py
=> [bin] limit step when averaging model

wenet/transducer/transducer.py
fix 'th_accuracy' not in transducer
=> fix 'th_accuracy' not in transducer

wenet/utils/init_model.py
https://github.com/wenet-e2e/wenet/issues/2350
=> [wenet] fix args.enc

wenet/transformer/decoder.py
https://github.com/wenet-e2e/wenet/pull/2351#discussion_r1500361138
这里直接给decoder一个参数，
=> [transformer] fix bidecoder sdpa

wenet/dataset/dataset.py, wenet/dataset/processor.py
原始的whisper（非whisper fintune）不pad的时候解码会重复：
pad：
=> [dataset] support pad or trim for whisper decoding

examples/aishell/whisper/local/modify_ckpt.py
As title described:
--remove_list and --add_list require checking for empty values.
=> fix whisper ckpt modify error

wenet/bin/recognize.py
=> 更新 recognize.py

wenet/transformer/attention.py
follow this  https://github.com/wenet-e2e/wenet/pull/2419
=> [transformer] fix sdpa mask for ShowRelAttention

wenet/utils/common.py
fix jit issue caused by if-else branch in `get_dtype_min()`
=> [runtime/libtorch] fix jit issue

examples/aishell/paraformer/README.md
after pr: https://github.com/wenet-e2e/wenet/pull/2431
=> fix modify

wenet/utils/train_utils.py
steps mode下 continue pretrain 可以显示正确的step, 以前显示的0/0
=> fix step in continue training  in steps mode

tools/analyze_dataset.py, tools/latency_metrics.py, wenet/text/tokenize_utils.py, wenet/utils/train_utils.py
follow this  https://github.com/wenet-e2e/wenet/pull/2456
=> [fix] fix copyright

wenet/transformer/embedding.py
=> fix rope pos embdining

wenet/transformer/attention.py
hidden_dim 可以和 n_head*head_dim 不相同
=> [transformer] fix mqa

wenet/utils/checkpoint.py
=> enable mmap in torch.load

examples/aishell/whisper/conf/ds_stage1.json, examples/aishell/whisper/conf/ds_stage2.json, examples/aishell/whisper/conf/ds_stage3.json
1. simplify stage1 config, remove useless args
2. add stage2 & stage3
=> [example] Add deespeed configs of different stages for illustrative purposes

examples/aishell/s0/run.sh, examples/aishell/whisper/run.sh, examples/wenetspeech/s0/conf/train_u2++_conformer.yaml, examples/wenetspeech/s0/run.sh, examples/wenetspeech/whisper/conf/finetune_whisper_largev3.yaml, examples/wenetspeech/whisper/run.sh
1. Large prefetch may cause OOM issue
2. Configure the epoch in yaml, instead of run.sh
=> [example] Fix prefetch and step_save

wenet/transformer/search.py
after https://github.com/wenet-e2e/wenet/pull/2481
=> [transformer] fix search after refactor cache

wenet/transformer/attention.py
after: https://github.com/wenet-e2e/wenet/pull/2497
=> [transformer] fix mqa in cross att

examples/aishell/whisper/conf/ds_stage1.json, examples/aishell/whisper/conf/ds_stage2.json, examples/aishell/whisper/conf/ds_stage3.json, examples/wenetspeech/whisper/conf/ds_stage1.json
- add `offload_optimizer` for stage1
- remove `offload_param` for stage2 (since param is not partitioned in stage2, offload_param is meaningless)
=> [deepspeed] update json config

wenet/utils/init_model.py
fix https://github.com/wenet-e2e/wenet/issues/2500
=> [onnx] clone weight for whisper

wenet/utils/train_utils.py
step模式，假设梯度累积为4，log interval 为100， 打印变成了0/25
修复后：
=> [wenet/utils/train_utils.py] fix log

wenet/transformer/attention.py
LLM选择softmax的时候保持高精度， 稳定模型在bf16的时候的训练
比如：
https://github.com/google/gemma_pytorch/blob/main/gemma/model.py#L288
=> [transformer] keep high precisioin in softmax

README.md
recomended -> recommended
aslo -> also
official -> official
=> fix: correct typos

wenet/dataset/processor.py
=> [Fix] Fix torchaudio load params

wenet/LLM/causallm_model.py, wenet/LLM/decoder.py, wenet/LLM/sampler.py, wenet/transformer/asr_model.py, wenet/transformer/attention.py, wenet/transformer/decoder.py, wenet/transformer/embedding.py, wenet/transformer/encoder_layer.py, wenet/transformer/norm.py, wenet/utils/fsdp_utils.py, wenet/utils/init_model.py, wenet/utils/rope_utils.py, wenet/utils/train_utils.py
拆分该pr：https://github.com/wenet-e2e/wenet/pull/2460
=> [LLM] support causallm model

wenet/bin/train.py
建议添加barrier，确保训练完成之后销毁process_group
=> [wenet/bin/train.py] add barrier before destory process group

test/wenet/text/test_hugging_face_tokenizer.py
try to pass unit test by fixed version
=> [test] fix version for transformers

requirements.txt, test/wenet/text/test_hugging_face_tokenizer.py
=> Revert "[test] fix version for transformers"

wenet/cli/model.py, wenet/cli/paraformer_model.py, wenet/utils/ctc_utils.py
[BAC009S0764W0121.wav](https://dataset-hub.oss-cn-hangzhou.aliyuncs.com/public-unzipped/speech_asr_speech_asr_aishell1_trainsets_speech_asr_aishell_testsets/speech_asr_aishell_testsets/wav/test/S0764/BAC009S0764W0121.wav)
``` bash
python wenet/cli/transcribe.py --align BAC009S0764W0121.wav --label 甚至出现交易几乎停滞的情况
```
40ms => 2ms
=> [utils] use force_align of torchaudio

test/wenet/dataset/test_datapipes.py, wenet/dataset/datapipes.py
=> [dataset ] support interleave dataset

runtime/ios/WenetDemo/WenetDemo/ViewController.swift, runtime/ios/WenetDemo/WenetDemo/wenet/wenet.mm
- Added logging.
- Replaced force unwrapping with safer optional binding techniques to prevent potential runtime crashes.
- Ensured proper memory management by using [weak self] in closures to avoid retain cycles and potential memory leaks.
=> [WenetDemo] improve safety and maintainability

.github/workflows/lint.yml, .github/workflows/unit_test.yml
=> [workflow] fix python env

wenet/cli/paraformer_model.py, wenet/paraformer/paraformer.py
=> [cli] fix ts

wenet/transformer/convolution.py
after this pr : https://github.com/wenet-e2e/wenet/pull/2681
=> fix convlution module norm dim

wenet/firered/attention.py, wenet/transformer/attention.py
Fixes https://github.com/wenet-e2e/wenet/issues/2699
=> Fix SDPA dropout rate

tools/cmvn_kaldi2json.py
=> Update cmvn_kaldi2json.py to fix #2712

wenet/text/char_tokenizer.py
=> [fix] minor fix char_tokenizer.py

wenet/cli/hub.py, wenet/firered/model.py, wenet/transformer/asr_model.py
=> [cli] support firered model

wenet/cli/hub.py, wenet/transformer/asr_model.py, wenet/transformer/search.py, wenet/whisper/convert_whisper_to_wenet_config_and_ckpt.py, wenet/whisper/whisper.py
=> [cli] support whisper
